// ============================================
// EARLOCK — DATA FILE
// Add new songs here. game.js handles all logic.
//
// Format: {title, artist, year}
// Append new entries at the bottom of SONGS.
// The game fetches a free 30s preview from iTunes automatically.
// No URLs needed — just title + artist is enough.
// ============================================

const SONGS = [
    // 2010s mainstream pop
    {title:"Blinding Lights", artist:"The Weeknd", year:2019},
    {title:"Shape of You", artist:"Ed Sheeran", year:2017},
    {title:"Dance Monkey", artist:"Tones and I", year:2019},
    {title:"Stay", artist:"The Kid LAROI", year:2021},
    {title:"Levitating", artist:"Dua Lipa", year:2020},
    {title:"drivers license", artist:"Olivia Rodrigo", year:2021},
    {title:"Watermelon Sugar", artist:"Harry Styles", year:2019},
    {title:"good 4 u", artist:"Olivia Rodrigo", year:2021},
    {title:"Heat Waves", artist:"Glass Animals", year:2020},
    {title:"Easy On Me", artist:"Adele", year:2021},
    {title:"As It Was", artist:"Harry Styles", year:2022},
    {title:"Anti-Hero", artist:"Taylor Swift", year:2022},
    {title:"Flowers", artist:"Miley Cyrus", year:2023},
    {title:"Cruel Summer", artist:"Taylor Swift", year:2019},
    {title:"Kill Bill", artist:"SZA", year:2022},
    {title:"Golden Hour", artist:"JVKE", year:2022},
    {title:"Calm Down", artist:"Rema", year:2022},
    {title:"Industry Baby", artist:"Lil Nas X", year:2021},
    {title:"Unholy", artist:"Sam Smith", year:2022},
    {title:"Montero", artist:"Lil Nas X", year:2021},
    {title:"Save Your Tears", artist:"The Weeknd", year:2021},
    {title:"abcdefu", artist:"GAYLE", year:2021},
    {title:"Butter", artist:"BTS", year:2021},
    {title:"Sunflower", artist:"Post Malone", year:2018},
    {title:"Bad Guy", artist:"Billie Eilish", year:2019},

    // More 2020s
    {title:"Positions", artist:"Ariana Grande", year:2020},
    {title:"Peaches", artist:"Justin Bieber", year:2021},
    {title:"Dynamite", artist:"BTS", year:2020},
    {title:"Mood", artist:"24kGoldn", year:2020},
    {title:"Essence", artist:"Wizkid", year:2020},
    {title:"Beggin", artist:"Maneskin", year:2021},
    {title:"Astronaut In The Ocean", artist:"Masked Wolf", year:2021},
    {title:"Permission to Dance", artist:"BTS", year:2021},
    {title:"Leave The Door Open", artist:"Silk Sonic", year:2021},
    {title:"Need To Know", artist:"Doja Cat", year:2021},
    {title:"Fancy Like", artist:"Walker Hayes", year:2021},
    {title:"Shivers", artist:"Ed Sheeran", year:2021},
    {title:"Bad Habits", artist:"Ed Sheeran", year:2021},
    {title:"Overpass Graffiti", artist:"Ed Sheeran", year:2021},
    {title:"happier than ever", artist:"Billie Eilish", year:2021},
    {title:"NDA", artist:"Billie Eilish", year:2021},
    {title:"Therefore I Am", artist:"Billie Eilish", year:2020},
    {title:"brutal", artist:"Olivia Rodrigo", year:2021},
    {title:"traitor", artist:"Olivia Rodrigo", year:2021},
    {title:"vampire", artist:"Olivia Rodrigo", year:2023},
    {title:"get him back!", artist:"Olivia Rodrigo", year:2023},
    {title:"Escapism", artist:"RAYE", year:2022},
    {title:"Creepin", artist:"Metro Boomin", year:2022},
    {title:"Rich Flex", artist:"Drake", year:2022},
    {title:"Jimmy Cooks", artist:"Drake", year:2022},
    {title:"Sprinter", artist:"Dave", year:2023},
    {title:"Knife Talk", artist:"Drake", year:2021},
    {title:"Moth To A Flame", artist:"Swedish House Mafia", year:2021},
    {title:"We Don't Talk About Bruno", artist:"Carolina Gaitan", year:2021},
    {title:"About Damn Time", artist:"Lizzo", year:2022},
    {title:"Running Up That Hill", artist:"Kate Bush", year:1985},
    {title:"Late Night Talking", artist:"Harry Styles", year:2022},
    {title:"Music For a Sushi Restaurant", artist:"Harry Styles", year:2022},
    {title:"Midnight Rain", artist:"Taylor Swift", year:2022},
    {title:"Lavender Haze", artist:"Taylor Swift", year:2022},
    {title:"Karma", artist:"Taylor Swift", year:2022},
    {title:"Snow On The Beach", artist:"Taylor Swift", year:2022},
    {title:"Shake It Off", artist:"Taylor Swift", year:2014},
    {title:"Blank Space", artist:"Taylor Swift", year:2014},
    {title:"Love Story", artist:"Taylor Swift", year:2008},
    {title:"Style", artist:"Taylor Swift", year:2014},
    {title:"Starboy", artist:"The Weeknd", year:2016},
    {title:"Call Out My Name", artist:"The Weeknd", year:2018},
    {title:"Die For You", artist:"The Weeknd", year:2016},
    {title:"Out of Time", artist:"The Weeknd", year:2022},
    {title:"popular", artist:"The Weeknd", year:2023},

    // 2010s bangers
    {title:"Rolling in the Deep", artist:"Adele", year:2010},
    {title:"Someone Like You", artist:"Adele", year:2011},
    {title:"Hello", artist:"Adele", year:2015},
    {title:"Uptown Funk", artist:"Mark Ronson", year:2014},
    {title:"Happy", artist:"Pharrell Williams", year:2013},
    {title:"Thinking Out Loud", artist:"Ed Sheeran", year:2014},
    {title:"Photograph", artist:"Ed Sheeran", year:2014},
    {title:"Perfect", artist:"Ed Sheeran", year:2017},
    {title:"Castle On The Hill", artist:"Ed Sheeran", year:2017},
    {title:"Old Town Road", artist:"Lil Nas X", year:2019},
    {title:"Rockstar", artist:"Post Malone", year:2017},
    {title:"Circles", artist:"Post Malone", year:2019},
    {title:"Better Now", artist:"Post Malone", year:2018},
    {title:"Psycho", artist:"Post Malone", year:2018},
    {title:"Congratulations", artist:"Post Malone", year:2018},
    {title:"One Dance", artist:"Drake", year:2016},
    {title:"God's Plan", artist:"Drake", year:2018},
    {title:"In My Feelings", artist:"Drake", year:2018},
    {title:"Nice For What", artist:"Drake", year:2018},
    {title:"Hotline Bling", artist:"Drake", year:2015},
    {title:"Despacito", artist:"Luis Fonsi", year:2017},
    {title:"Sorry", artist:"Justin Bieber", year:2015},
    {title:"Love Yourself", artist:"Justin Bieber", year:2015},
    {title:"What Do You Mean", artist:"Justin Bieber", year:2015},
    {title:"Intentions", artist:"Justin Bieber", year:2020},
    {title:"Havana", artist:"Camila Cabello", year:2017},
    {title:"Never Be The Same", artist:"Camila Cabello", year:2017},
    {title:"New Rules", artist:"Dua Lipa", year:2017},
    {title:"One Kiss", artist:"Dua Lipa", year:2018},
    {title:"Physical", artist:"Dua Lipa", year:2020},
    {title:"Don't Start Now", artist:"Dua Lipa", year:2019},
    {title:"Senorita", artist:"Shawn Mendes", year:2019},
    {title:"Stitches", artist:"Shawn Mendes", year:2015},
    {title:"There's Nothing Holdin' Me Back", artist:"Shawn Mendes", year:2017},
    {title:"7 Years", artist:"Lukas Graham", year:2015},
    {title:"Stressed Out", artist:"Twenty One Pilots", year:2015},
    {title:"Heathens", artist:"Twenty One Pilots", year:2016},
    {title:"Ride", artist:"Twenty One Pilots", year:2015},
    {title:"Believer", artist:"Imagine Dragons", year:2017},
    {title:"Thunder", artist:"Imagine Dragons", year:2017},
    {title:"Radioactive", artist:"Imagine Dragons", year:2012},
    {title:"Natural", artist:"Imagine Dragons", year:2018},
    {title:"Demons", artist:"Imagine Dragons", year:2012},
    {title:"Sugar", artist:"Maroon 5", year:2014},
    {title:"Girls Like You", artist:"Maroon 5", year:2018},
    {title:"Moves Like Jagger", artist:"Maroon 5", year:2011},
    {title:"Animals", artist:"Maroon 5", year:2014},
    {title:"Wrecking Ball", artist:"Miley Cyrus", year:2013},
    {title:"We Can't Stop", artist:"Miley Cyrus", year:2013},
    {title:"Problem", artist:"Ariana Grande", year:2014},
    {title:"Thank U Next", artist:"Ariana Grande", year:2018},
    {title:"7 Rings", artist:"Ariana Grande", year:2019},
    {title:"No Tears Left To Cry", artist:"Ariana Grande", year:2018},
    {title:"Into You", artist:"Ariana Grande", year:2016},
    {title:"Side To Side", artist:"Ariana Grande", year:2016},
    {title:"God is a woman", artist:"Ariana Grande", year:2018},

    // Hip-hop & R&B
    {title:"Sicko Mode", artist:"Travis Scott", year:2018},
    {title:"Goosebumps", artist:"Travis Scott", year:2016},
    {title:"Antidote", artist:"Travis Scott", year:2015},
    {title:"HIGHEST IN THE ROOM", artist:"Travis Scott", year:2019},
    {title:"DNA", artist:"Kendrick Lamar", year:2017},
    {title:"HUMBLE", artist:"Kendrick Lamar", year:2017},
    {title:"Not Like Us", artist:"Kendrick Lamar", year:2024},
    {title:"All The Stars", artist:"Kendrick Lamar", year:2018},
    {title:"Savage", artist:"Megan Thee Stallion", year:2020},
    {title:"WAP", artist:"Cardi B", year:2020},
    {title:"Bodak Yellow", artist:"Cardi B", year:2017},
    {title:"I Like It", artist:"Cardi B", year:2018},
    {title:"Rockstar", artist:"DaBaby", year:2020},
    {title:"BOP", artist:"DaBaby", year:2019},
    {title:"Franchise", artist:"Travis Scott", year:2020},
    {title:"Lemon", artist:"N.E.R.D", year:2017},
    {title:"MIDDLE CHILD", artist:"J. Cole", year:2019},
    {title:"No Role Modelz", artist:"J. Cole", year:2014},

    // UK / Grime / Afrobeats
    {title:"Shutdown", artist:"Skepta", year:2015},
    {title:"Man's Not Hot", artist:"Big Shaq", year:2017},
    {title:"German Whip", artist:"Meridian Dan", year:2014},
    {title:"Vossi Bop", artist:"Stormzy", year:2019},
    {title:"Blinded By Your Grace", artist:"Stormzy", year:2017},
    {title:"Superheroes", artist:"Stormzy", year:2023},
    {title:"Little Bit of Love", artist:"Tom Grennan", year:2021},
    {title:"Midnight", artist:"Russ Millions", year:2021},
    {title:"Afro Nation", artist:"WizKid", year:2021},
    {title:"Waterfalls", artist:"TLC", year:1994},

    // 2000s nostalgia
    {title:"Crazy In Love", artist:"Beyonce", year:2003},
    {title:"Halo", artist:"Beyonce", year:2008},
    {title:"Single Ladies", artist:"Beyonce", year:2008},
    {title:"Irreplaceable", artist:"Beyonce", year:2006},
    {title:"Telephone", artist:"Lady Gaga", year:2009},
    {title:"Bad Romance", artist:"Lady Gaga", year:2009},
    {title:"Just Dance", artist:"Lady Gaga", year:2008},
    {title:"Poker Face", artist:"Lady Gaga", year:2008},
    {title:"Umbrella", artist:"Rihanna", year:2007},
    {title:"Diamonds", artist:"Rihanna", year:2012},
    {title:"We Found Love", artist:"Rihanna", year:2011},
    {title:"Only Girl", artist:"Rihanna", year:2010},
    {title:"Disturbia", artist:"Rihanna", year:2008},
    {title:"California Gurls", artist:"Katy Perry", year:2010},
    {title:"Roar", artist:"Katy Perry", year:2013},
    {title:"Firework", artist:"Katy Perry", year:2010},
    {title:"Dark Horse", artist:"Katy Perry", year:2013},
    {title:"Teenage Dream", artist:"Katy Perry", year:2010},
    {title:"Party In The U.S.A.", artist:"Miley Cyrus", year:2009},
    {title:"Since U Been Gone", artist:"Kelly Clarkson", year:2004},
    {title:"Complicated", artist:"Avril Lavigne", year:2002},
    {title:"Girlfriend", artist:"Avril Lavigne", year:2007},
    {title:"Sk8er Boi", artist:"Avril Lavigne", year:2002},
    {title:"In Da Club", artist:"50 Cent", year:2003},
    {title:"Yeah!", artist:"Usher", year:2004},
    {title:"My Boo", artist:"Usher", year:2004},
    {title:"Burn", artist:"Usher", year:2004},
    {title:"Gold Digger", artist:"Kanye West", year:2005},
    {title:"Stronger", artist:"Kanye West", year:2007},
    {title:"Heartless", artist:"Kanye West", year:2008},
    {title:"Lose Yourself", artist:"Eminem", year:2002},
    {title:"Without Me", artist:"Eminem", year:2002},
    {title:"The Real Slim Shady", artist:"Eminem", year:2000},

    // 90s classics
    {title:"...Baby One More Time", artist:"Britney Spears", year:1998},
    {title:"Toxic", artist:"Britney Spears", year:2003},
    {title:"Oops!... I Did It Again", artist:"Britney Spears", year:2000},
    {title:"Wannabe", artist:"Spice Girls", year:1996},
    {title:"2 Become 1", artist:"Spice Girls", year:1996},
    {title:"Say You'll Be There", artist:"Spice Girls", year:1996},
    {title:"Quit Playing Games", artist:"Backstreet Boys", year:1996},
    {title:"I Want It That Way", artist:"Backstreet Boys", year:1999},
    {title:"Everybody", artist:"Backstreet Boys", year:1997},
    {title:"Tearin' Up My Heart", artist:"NSYNC", year:1997},
    {title:"Bye Bye Bye", artist:"NSYNC", year:2000},
    {title:"No Scrubs", artist:"TLC", year:1999},
    {title:"Creep", artist:"TLC", year:1992},
    {title:"Smells Like Teen Spirit", artist:"Nirvana", year:1991},
    {title:"Come As You Are", artist:"Nirvana", year:1991},
    {title:"Under The Bridge", artist:"Red Hot Chili Peppers", year:1991},
    {title:"Wonderwall", artist:"Oasis", year:1995},
    {title:"Don't Look Back In Anger", artist:"Oasis", year:1996},
    {title:"Champagne Supernova", artist:"Oasis", year:1995},
    {title:"Losing My Religion", artist:"R.E.M.", year:1991},
    {title:"Semi-Charmed Life", artist:"Third Eye Blind", year:1997},
    {title:"MMMBop", artist:"Hanson", year:1997},
    {title:"Killing Me Softly", artist:"Fugees", year:1996},
    {title:"Gangsta's Paradise", artist:"Coolio", year:1995},
    {title:"Rhythm Is a Dancer", artist:"Snap!", year:1992},
    {title:"Freed from Desire", artist:"Gala", year:1997},

    // 80s icons
    {title:"Take On Me", artist:"a-ha", year:1985},
    {title:"Don't You Want Me", artist:"Human League", year:1981},
    {title:"Sweet Child O' Mine", artist:"Guns N' Roses", year:1987},
    {title:"November Rain", artist:"Guns N' Roses", year:1991},
    {title:"Livin' on a Prayer", artist:"Bon Jovi", year:1986},
    {title:"You Give Love a Bad Name", artist:"Bon Jovi", year:1986},
    {title:"Total Eclipse of the Heart", artist:"Bonnie Tyler", year:1983},
    {title:"Africa", artist:"Toto", year:1982},
    {title:"Don't Stop Believin'", artist:"Journey", year:1981},
    {title:"Eye of the Tiger", artist:"Survivor", year:1982},
    {title:"Girls Just Wanna Have Fun", artist:"Cyndi Lauper", year:1983},
    {title:"Time After Time", artist:"Cyndi Lauper", year:1983},
    {title:"Like a Prayer", artist:"Madonna", year:1989},
    {title:"Material Girl", artist:"Madonna", year:1984},
    {title:"Papa Don't Preach", artist:"Madonna", year:1986},
    {title:"Wake Me Up Before You Go-Go", artist:"Wham!", year:1984},
    {title:"Careless Whisper", artist:"George Michael", year:1984},
    {title:"Faith", artist:"George Michael", year:1987},
    {title:"Billie Jean", artist:"Michael Jackson", year:1982},
    {title:"Thriller", artist:"Michael Jackson", year:1982},
    {title:"Beat It", artist:"Michael Jackson", year:1982},
    {title:"Man In The Mirror", artist:"Michael Jackson", year:1987},
    {title:"Smooth Criminal", artist:"Michael Jackson", year:1987},
    {title:"Bohemian Rhapsody", artist:"Queen", year:1975},
    {title:"Don't Stop Me Now", artist:"Queen", year:1978},
    {title:"We Will Rock You", artist:"Queen", year:1977},
    {title:"Radio Ga Ga", artist:"Queen", year:1984},
    {title:"Under Pressure", artist:"Queen", year:1981},

    // Dance / Electronic
    {title:"One More Time", artist:"Daft Punk", year:2000},
    {title:"Get Lucky", artist:"Daft Punk", year:2013},
    {title:"Instant Crush", artist:"Daft Punk", year:2013},
    {title:"Levels", artist:"Avicii", year:2011},
    {title:"Wake Me Up", artist:"Avicii", year:2013},
    {title:"Hey Brother", artist:"Avicii", year:2013},
    {title:"Lean On", artist:"Major Lazer", year:2015},
    {title:"Cold Water", artist:"Major Lazer", year:2016},
    {title:"Animals", artist:"Martin Garrix", year:2013},
    {title:"In The Name Of Love", artist:"Martin Garrix", year:2016},
    {title:"Titanium", artist:"David Guetta", year:2011},
    {title:"Turn Me On", artist:"David Guetta", year:2011},
    {title:"Play Hard", artist:"David Guetta", year:2013},
    {title:"Clarity", artist:"Zedd", year:2012},
    {title:"Beautiful Now", artist:"Zedd", year:2015},
    {title:"The Middle", artist:"Zedd", year:2018},
    {title:"Skyfall", artist:"Adele", year:2012},
    {title:"Stay With Me", artist:"Sam Smith", year:2014},
    {title:"Writing's On The Wall", artist:"Sam Smith", year:2015},
    {title:"Latch", artist:"Disclosure", year:2012},
    {title:"Magnets", artist:"Disclosure", year:2015},
    {title:"Rather Be", artist:"Clean Bandit", year:2014},
    {title:"Rockabye", artist:"Clean Bandit", year:2016},
    {title:"Symphony", artist:"Clean Bandit", year:2017},
    {title:"Solo", artist:"Clean Bandit", year:2018},
];
