// ============================================
// EARLOCK — DATA FILE
// Add new songs here. game.js handles all logic.
//
// Format: {title, artist, year}
// Append new entries at the bottom of SONGS.
// The game fetches a free 30s preview from iTunes automatically.
// No URLs needed — just title + artist is enough.
// ============================================

const SONGS = [
    // 2010s mainstream pop
    {title:"Blinding Lights", artist:"The Weeknd", year:2019},
    {title:"Shape of You", artist:"Ed Sheeran", year:2017},
    {title:"Dance Monkey", artist:"Tones and I", year:2019},
    {title:"Stay", artist:"The Kid LAROI", year:2021},
    {title:"Levitating", artist:"Dua Lipa", year:2020},
    {title:"drivers license", artist:"Olivia Rodrigo", year:2021},
    {title:"Watermelon Sugar", artist:"Harry Styles", year:2019},
    {title:"good 4 u", artist:"Olivia Rodrigo", year:2021},
    {title:"Heat Waves", artist:"Glass Animals", year:2020},
    {title:"Easy On Me", artist:"Adele", year:2021},
    {title:"As It Was", artist:"Harry Styles", year:2022},
    {title:"Anti-Hero", artist:"Taylor Swift", year:2022},
    {title:"Flowers", artist:"Miley Cyrus", year:2023},
    {title:"Cruel Summer", artist:"Taylor Swift", year:2019},
    {title:"Kill Bill", artist:"SZA", year:2022},
    {title:"Golden Hour", artist:"JVKE", year:2022},
    {title:"Calm Down", artist:"Rema", year:2022},
    {title:"Industry Baby", artist:"Lil Nas X", year:2021},
    {title:"Unholy", artist:"Sam Smith", year:2022},
    {title:"Montero", artist:"Lil Nas X", year:2021},
    {title:"Save Your Tears", artist:"The Weeknd", year:2021},
    {title:"abcdefu", artist:"GAYLE", year:2021},
    {title:"Butter", artist:"BTS", year:2021},
    {title:"Sunflower", artist:"Post Malone", year:2018},
    {title:"Bad Guy", artist:"Billie Eilish", year:2019},

    // More 2020s
    {title:"Positions", artist:"Ariana Grande", year:2020},
    {title:"Peaches", artist:"Justin Bieber", year:2021},
    {title:"Dynamite", artist:"BTS", year:2020},
    {title:"Mood", artist:"24kGoldn", year:2020},
    {title:"Essence", artist:"Wizkid", year:2020},
    {title:"Beggin", artist:"Maneskin", year:2021},
    {title:"Astronaut In The Ocean", artist:"Masked Wolf", year:2021},
    {title:"Permission to Dance", artist:"BTS", year:2021},
    {title:"Leave The Door Open", artist:"Silk Sonic", year:2021},
    {title:"Need To Know", artist:"Doja Cat", year:2021},
    {title:"Fancy Like", artist:"Walker Hayes", year:2021},
    {title:"Shivers", artist:"Ed Sheeran", year:2021},
    {title:"Bad Habits", artist:"Ed Sheeran", year:2021},
    {title:"Overpass Graffiti", artist:"Ed Sheeran", year:2021},
    {title:"happier than ever", artist:"Billie Eilish", year:2021},
    {title:"NDA", artist:"Billie Eilish", year:2021},
    {title:"Therefore I Am", artist:"Billie Eilish", year:2020},
    {title:"brutal", artist:"Olivia Rodrigo", year:2021},
    {title:"traitor", artist:"Olivia Rodrigo", year:2021},
    {title:"vampire", artist:"Olivia Rodrigo", year:2023},
    {title:"get him back!", artist:"Olivia Rodrigo", year:2023},
    {title:"Escapism", artist:"RAYE", year:2022},
    {title:"Creepin", artist:"Metro Boomin", year:2022},
    {title:"Rich Flex", artist:"Drake", year:2022},
    {title:"Jimmy Cooks", artist:"Drake", year:2022},
    {title:"Sprinter", artist:"Dave", year:2023},
    {title:"Knife Talk", artist:"Drake", year:2021},
    {title:"Moth To A Flame", artist:"Swedish House Mafia", year:2021},
    {title:"We Don't Talk About Bruno", artist:"Carolina Gaitan", year:2021},
    {title:"About Damn Time", artist:"Lizzo", year:2022},
    {title:"Running Up That Hill", artist:"Kate Bush", year:1985},
    {title:"Late Night Talking", artist:"Harry Styles", year:2022},
    {title:"Music For a Sushi Restaurant", artist:"Harry Styles", year:2022},
    {title:"Midnight Rain", artist:"Taylor Swift", year:2022},
    {title:"Lavender Haze", artist:"Taylor Swift", year:2022},
    {title:"Karma", artist:"Taylor Swift", year:2022},
    {title:"Snow On The Beach", artist:"Taylor Swift", year:2022},
    {title:"Shake It Off", artist:"Taylor Swift", year:2014},
    {title:"Blank Space", artist:"Taylor Swift", year:2014},
    {title:"Love Story", artist:"Taylor Swift", year:2008},
    {title:"Style", artist:"Taylor Swift", year:2014},
    {title:"Starboy", artist:"The Weeknd", year:2016},
    {title:"Call Out My Name", artist:"The Weeknd", year:2018},
    {title:"Die For You", artist:"The Weeknd", year:2016},
    {title:"Out of Time", artist:"The Weeknd", year:2022},
    {title:"popular", artist:"The Weeknd", year:2023},

    // 2010s bangers
    {title:"Rolling in the Deep", artist:"Adele", year:2010},
    {title:"Someone Like You", artist:"Adele", year:2011},
    {title:"Hello", artist:"Adele", year:2015},
    {title:"Uptown Funk", artist:"Mark Ronson", year:2014},
    {title:"Happy", artist:"Pharrell Williams", year:2013},
    {title:"Thinking Out Loud", artist:"Ed Sheeran", year:2014},
    {title:"Photograph", artist:"Ed Sheeran", year:2014},
    {title:"Perfect", artist:"Ed Sheeran", year:2017},
    {title:"Castle On The Hill", artist:"Ed Sheeran", year:2017},
    {title:"Old Town Road", artist:"Lil Nas X", year:2019},
    {title:"Rockstar", artist:"Post Malone", year:2017},
    {title:"Circles", artist:"Post Malone", year:2019},
    {title:"Better Now", artist:"Post Malone", year:2018},
    {title:"Psycho", artist:"Post Malone", year:2018},
    {title:"Congratulations", artist:"Post Malone", year:2018},
    {title:"One Dance", artist:"Drake", year:2016},
    {title:"God's Plan", artist:"Drake", year:2018},
    {title:"In My Feelings", artist:"Drake", year:2018},
    {title:"Nice For What", artist:"Drake", year:2018},
    {title:"Hotline Bling", artist:"Drake", year:2015},
    {title:"Despacito", artist:"Luis Fonsi", year:2017},
    {title:"Sorry", artist:"Justin Bieber", year:2015},
    {title:"Love Yourself", artist:"Justin Bieber", year:2015},
    {title:"What Do You Mean", artist:"Justin Bieber", year:2015},
    {title:"Intentions", artist:"Justin Bieber", year:2020},
    {title:"Havana", artist:"Camila Cabello", year:2017},
    {title:"Never Be The Same", artist:"Camila Cabello", year:2017},
    {title:"New Rules", artist:"Dua Lipa", year:2017},
    {title:"One Kiss", artist:"Dua Lipa", year:2018},
    {title:"Physical", artist:"Dua Lipa", year:2020},
    {title:"Don't Start Now", artist:"Dua Lipa", year:2019},
    {title:"Senorita", artist:"Shawn Mendes", year:2019},
    {title:"Stitches", artist:"Shawn Mendes", year:2015},
    {title:"There's Nothing Holdin' Me Back", artist:"Shawn Mendes", year:2017},
    {title:"7 Years", artist:"Lukas Graham", year:2015},
    {title:"Stressed Out", artist:"Twenty One Pilots", year:2015},
    {title:"Heathens", artist:"Twenty One Pilots", year:2016},
    {title:"Ride", artist:"Twenty One Pilots", year:2015},
    {title:"Believer", artist:"Imagine Dragons", year:2017},
    {title:"Thunder", artist:"Imagine Dragons", year:2017},
    {title:"Radioactive", artist:"Imagine Dragons", year:2012},
    {title:"Natural", artist:"Imagine Dragons", year:2018},
    {title:"Demons", artist:"Imagine Dragons", year:2012},
    {title:"Sugar", artist:"Maroon 5", year:2014},
    {title:"Girls Like You", artist:"Maroon 5", year:2018},
    {title:"Moves Like Jagger", artist:"Maroon 5", year:2011},
    {title:"Animals", artist:"Maroon 5", year:2014},
    {title:"Wrecking Ball", artist:"Miley Cyrus", year:2013},
    {title:"We Can't Stop", artist:"Miley Cyrus", year:2013},
    {title:"Problem", artist:"Ariana Grande", year:2014},
    {title:"Thank U Next", artist:"Ariana Grande", year:2018},
    {title:"7 Rings", artist:"Ariana Grande", year:2019},
    {title:"No Tears Left To Cry", artist:"Ariana Grande", year:2018},
    {title:"Into You", artist:"Ariana Grande", year:2016},
    {title:"Side To Side", artist:"Ariana Grande", year:2016},
    {title:"God is a woman", artist:"Ariana Grande", year:2018},

    // Hip-hop & R&B
    {title:"Sicko Mode", artist:"Travis Scott", year:2018},
    {title:"Goosebumps", artist:"Travis Scott", year:2016},
    {title:"Antidote", artist:"Travis Scott", year:2015},
    {title:"HIGHEST IN THE ROOM", artist:"Travis Scott", year:2019},
    {title:"DNA", artist:"Kendrick Lamar", year:2017},
    {title:"HUMBLE", artist:"Kendrick Lamar", year:2017},
    {title:"Not Like Us", artist:"Kendrick Lamar", year:2024},
    {title:"All The Stars", artist:"Kendrick Lamar", year:2018},
    {title:"Savage", artist:"Megan Thee Stallion", year:2020},
    {title:"WAP", artist:"Cardi B", year:2020},
    {title:"Bodak Yellow", artist:"Cardi B", year:2017},
    {title:"I Like It", artist:"Cardi B", year:2018},
    {title:"Rockstar", artist:"DaBaby", year:2020},
    {title:"BOP", artist:"DaBaby", year:2019},
    {title:"Franchise", artist:"Travis Scott", year:2020},
    {title:"Lemon", artist:"N.E.R.D", year:2017},
    {title:"MIDDLE CHILD", artist:"J. Cole", year:2019},
    {title:"No Role Modelz", artist:"J. Cole", year:2014},

    // UK / Grime / Afrobeats
    {title:"Shutdown", artist:"Skepta", year:2015},
    {title:"Man's Not Hot", artist:"Big Shaq", year:2017},
    {title:"German Whip", artist:"Meridian Dan", year:2014},
    {title:"Vossi Bop", artist:"Stormzy", year:2019},
    {title:"Blinded By Your Grace", artist:"Stormzy", year:2017},
    {title:"Superheroes", artist:"Stormzy", year:2023},
    {title:"Little Bit of Love", artist:"Tom Grennan", year:2021},
    {title:"Midnight", artist:"Russ Millions", year:2021},
    {title:"Afro Nation", artist:"WizKid", year:2021},
    {title:"Waterfalls", artist:"TLC", year:1994},

    // 2000s nostalgia
    {title:"Crazy In Love", artist:"Beyonce", year:2003},
    {title:"Halo", artist:"Beyonce", year:2008},
    {title:"Single Ladies", artist:"Beyonce", year:2008},
    {title:"Irreplaceable", artist:"Beyonce", year:2006},
    {title:"Telephone", artist:"Lady Gaga", year:2009},
    {title:"Bad Romance", artist:"Lady Gaga", year:2009},
    {title:"Just Dance", artist:"Lady Gaga", year:2008},
    {title:"Poker Face", artist:"Lady Gaga", year:2008},
    {title:"Umbrella", artist:"Rihanna", year:2007},
    {title:"Diamonds", artist:"Rihanna", year:2012},
    {title:"We Found Love", artist:"Rihanna", year:2011},
    {title:"Only Girl", artist:"Rihanna", year:2010},
    {title:"Disturbia", artist:"Rihanna", year:2008},
    {title:"California Gurls", artist:"Katy Perry", year:2010},
    {title:"Roar", artist:"Katy Perry", year:2013},
    {title:"Firework", artist:"Katy Perry", year:2010},
    {title:"Dark Horse", artist:"Katy Perry", year:2013},
    {title:"Teenage Dream", artist:"Katy Perry", year:2010},
    {title:"Party In The U.S.A.", artist:"Miley Cyrus", year:2009},
    {title:"Since U Been Gone", artist:"Kelly Clarkson", year:2004},
    {title:"Complicated", artist:"Avril Lavigne", year:2002},
    {title:"Girlfriend", artist:"Avril Lavigne", year:2007},
    {title:"Sk8er Boi", artist:"Avril Lavigne", year:2002},
    {title:"In Da Club", artist:"50 Cent", year:2003},
    {title:"Yeah!", artist:"Usher", year:2004},
    {title:"My Boo", artist:"Usher", year:2004},
    {title:"Burn", artist:"Usher", year:2004},
    {title:"Gold Digger", artist:"Kanye West", year:2005},
    {title:"Stronger", artist:"Kanye West", year:2007},
    {title:"Heartless", artist:"Kanye West", year:2008},
    {title:"Lose Yourself", artist:"Eminem", year:2002},
    {title:"Without Me", artist:"Eminem", year:2002},
    {title:"The Real Slim Shady", artist:"Eminem", year:2000},

    // 90s classics
    {title:"...Baby One More Time", artist:"Britney Spears", year:1998},
    {title:"Toxic", artist:"Britney Spears", year:2003},
    {title:"Oops!... I Did It Again", artist:"Britney Spears", year:2000},
    {title:"Wannabe", artist:"Spice Girls", year:1996},
    {title:"2 Become 1", artist:"Spice Girls", year:1996},
    {title:"Say You'll Be There", artist:"Spice Girls", year:1996},
    {title:"Quit Playing Games", artist:"Backstreet Boys", year:1996},
    {title:"I Want It That Way", artist:"Backstreet Boys", year:1999},
    {title:"Everybody", artist:"Backstreet Boys", year:1997},
    {title:"Tearin' Up My Heart", artist:"NSYNC", year:1997},
    {title:"Bye Bye Bye", artist:"NSYNC", year:2000},
    {title:"No Scrubs", artist:"TLC", year:1999},
    {title:"Creep", artist:"TLC", year:1992},
    {title:"Smells Like Teen Spirit", artist:"Nirvana", year:1991},
    {title:"Come As You Are", artist:"Nirvana", year:1991},
    {title:"Under The Bridge", artist:"Red Hot Chili Peppers", year:1991},
    {title:"Wonderwall", artist:"Oasis", year:1995},
    {title:"Don't Look Back In Anger", artist:"Oasis", year:1996},
    {title:"Champagne Supernova", artist:"Oasis", year:1995},
    {title:"Losing My Religion", artist:"R.E.M.", year:1991},
    {title:"Semi-Charmed Life", artist:"Third Eye Blind", year:1997},
    {title:"MMMBop", artist:"Hanson", year:1997},
    {title:"Killing Me Softly", artist:"Fugees", year:1996},
    {title:"Gangsta's Paradise", artist:"Coolio", year:1995},
    {title:"Rhythm Is a Dancer", artist:"Snap!", year:1992},
    {title:"Freed from Desire", artist:"Gala", year:1997},

    // 80s icons
    {title:"Take On Me", artist:"a-ha", year:1985},
    {title:"Don't You Want Me", artist:"Human League", year:1981},
    {title:"Sweet Child O' Mine", artist:"Guns N' Roses", year:1987},
    {title:"November Rain", artist:"Guns N' Roses", year:1991},
    {title:"Livin' on a Prayer", artist:"Bon Jovi", year:1986},
    {title:"You Give Love a Bad Name", artist:"Bon Jovi", year:1986},
    {title:"Total Eclipse of the Heart", artist:"Bonnie Tyler", year:1983},
    {title:"Africa", artist:"Toto", year:1982},
    {title:"Don't Stop Believin'", artist:"Journey", year:1981},
    {title:"Eye of the Tiger", artist:"Survivor", year:1982},
    {title:"Girls Just Wanna Have Fun", artist:"Cyndi Lauper", year:1983},
    {title:"Time After Time", artist:"Cyndi Lauper", year:1983},
    {title:"Like a Prayer", artist:"Madonna", year:1989},
    {title:"Material Girl", artist:"Madonna", year:1984},
    {title:"Papa Don't Preach", artist:"Madonna", year:1986},
    {title:"Wake Me Up Before You Go-Go", artist:"Wham!", year:1984},
    {title:"Careless Whisper", artist:"George Michael", year:1984},
    {title:"Faith", artist:"George Michael", year:1987},
    {title:"Billie Jean", artist:"Michael Jackson", year:1982},
    {title:"Thriller", artist:"Michael Jackson", year:1982},
    {title:"Beat It", artist:"Michael Jackson", year:1982},
    {title:"Man In The Mirror", artist:"Michael Jackson", year:1987},
    {title:"Smooth Criminal", artist:"Michael Jackson", year:1987},
    {title:"Bohemian Rhapsody", artist:"Queen", year:1975},
    {title:"Don't Stop Me Now", artist:"Queen", year:1978},
    {title:"We Will Rock You", artist:"Queen", year:1977},
    {title:"Radio Ga Ga", artist:"Queen", year:1984},
    {title:"Under Pressure", artist:"Queen", year:1981},

    // Dance / Electronic
    {title:"One More Time", artist:"Daft Punk", year:2000},
    {title:"Get Lucky", artist:"Daft Punk", year:2013},
    {title:"Instant Crush", artist:"Daft Punk", year:2013},
    {title:"Levels", artist:"Avicii", year:2011},
    {title:"Wake Me Up", artist:"Avicii", year:2013},
    {title:"Hey Brother", artist:"Avicii", year:2013},
    {title:"Lean On", artist:"Major Lazer", year:2015},
    {title:"Cold Water", artist:"Major Lazer", year:2016},
    {title:"Animals", artist:"Martin Garrix", year:2013},
    {title:"In The Name Of Love", artist:"Martin Garrix", year:2016},
    {title:"Titanium", artist:"David Guetta", year:2011},
    {title:"Turn Me On", artist:"David Guetta", year:2011},
    {title:"Play Hard", artist:"David Guetta", year:2013},
    {title:"Clarity", artist:"Zedd", year:2012},
    {title:"Beautiful Now", artist:"Zedd", year:2015},
    {title:"The Middle", artist:"Zedd", year:2018},
    {title:"Skyfall", artist:"Adele", year:2012},
    {title:"Stay With Me", artist:"Sam Smith", year:2014},
    {title:"Writing's On The Wall", artist:"Sam Smith", year:2015},
    {title:"Latch", artist:"Disclosure", year:2012},
    {title:"Magnets", artist:"Disclosure", year:2015},
    {title:"Rather Be", artist:"Clean Bandit", year:2014},
    {title:"Rockabye", artist:"Clean Bandit", year:2016},
    {title:"Symphony", artist:"Clean Bandit", year:2017},
    {title:"Solo", artist:"Clean Bandit", year:2018},

    // Bruno Mars
    {title:"Just The Way You Are", artist:"Bruno Mars", year:2010},
    {title:"Grenade", artist:"Bruno Mars", year:2010},
    {title:"Locked Out of Heaven", artist:"Bruno Mars", year:2012},
    {title:"When I Was Your Man", artist:"Bruno Mars", year:2012},
    {title:"Treasure", artist:"Bruno Mars", year:2012},
    {title:"24K Magic", artist:"Bruno Mars", year:2016},
    {title:"Finesse", artist:"Bruno Mars", year:2017},
    {title:"That's What I Like", artist:"Bruno Mars", year:2016},
    {title:"Count on Me", artist:"Bruno Mars", year:2010},
    {title:"The Lazy Song", artist:"Bruno Mars", year:2010},

    // Charlie Puth / Lewis Capaldi / Khalid / Halsey
    {title:"Attention", artist:"Charlie Puth", year:2017},
    {title:"We Don't Talk Anymore", artist:"Charlie Puth", year:2016},
    {title:"One Call Away", artist:"Charlie Puth", year:2015},
    {title:"Light Switch", artist:"Charlie Puth", year:2022},
    {title:"See You Again", artist:"Charlie Puth", year:2015},
    {title:"Someone You Loved", artist:"Lewis Capaldi", year:2018},
    {title:"Before You Go", artist:"Lewis Capaldi", year:2019},
    {title:"Bruises", artist:"Lewis Capaldi", year:2017},
    {title:"Young Dumb & Broke", artist:"Khalid", year:2017},
    {title:"Location", artist:"Khalid", year:2016},
    {title:"Talk", artist:"Khalid", year:2019},
    {title:"Better", artist:"Khalid", year:2019},
    {title:"Saturday Nights", artist:"Khalid", year:2018},
    {title:"Without Me", artist:"Halsey", year:2018},
    {title:"Graveyard", artist:"Halsey", year:2020},
    {title:"Bad at Love", artist:"Halsey", year:2017},
    {title:"Colors", artist:"Halsey", year:2014},
    {title:"Now or Never", artist:"Halsey", year:2017},

    // More Billie Eilish
    {title:"Ocean Eyes", artist:"Billie Eilish", year:2016},
    {title:"Lovely", artist:"Billie Eilish", year:2018},
    {title:"All the Good Girls Go to Hell", artist:"Billie Eilish", year:2019},
    {title:"My Future", artist:"Billie Eilish", year:2020},
    {title:"Your Power", artist:"Billie Eilish", year:2021},
    {title:"What Was I Made For", artist:"Billie Eilish", year:2023},

    // More Taylor Swift
    {title:"We Are Never Ever Getting Back Together", artist:"Taylor Swift", year:2012},
    {title:"You Belong With Me", artist:"Taylor Swift", year:2009},
    {title:"22", artist:"Taylor Swift", year:2012},
    {title:"I Knew You Were Trouble", artist:"Taylor Swift", year:2012},
    {title:"All Too Well", artist:"Taylor Swift", year:2012},
    {title:"Out of the Woods", artist:"Taylor Swift", year:2014},
    {title:"Cardigan", artist:"Taylor Swift", year:2020},
    {title:"willow", artist:"Taylor Swift", year:2020},
    {title:"Enchanted", artist:"Taylor Swift", year:2010},
    {title:"Fearless", artist:"Taylor Swift", year:2008},
    {title:"Long Live", artist:"Taylor Swift", year:2010},
    {title:"Speak Now", artist:"Taylor Swift", year:2010},

    // More Harry Styles
    {title:"Adore You", artist:"Harry Styles", year:2019},
    {title:"Golden", artist:"Harry Styles", year:2019},
    {title:"Falling", artist:"Harry Styles", year:2019},
    {title:"Sign of the Times", artist:"Harry Styles", year:2017},
    {title:"Kiwi", artist:"Harry Styles", year:2017},

    // More The Weeknd
    {title:"Can't Feel My Face", artist:"The Weeknd", year:2015},
    {title:"I Feel It Coming", artist:"The Weeknd", year:2016},
    {title:"Earned It", artist:"The Weeknd", year:2015},
    {title:"In The Night", artist:"The Weeknd", year:2015},
    {title:"Often", artist:"The Weeknd", year:2014},
    {title:"Take My Breath", artist:"The Weeknd", year:2021},

    // More Ed Sheeran
    {title:"Lego House", artist:"Ed Sheeran", year:2011},
    {title:"The A Team", artist:"Ed Sheeran", year:2011},
    {title:"I See Fire", artist:"Ed Sheeran", year:2013},
    {title:"Galway Girl", artist:"Ed Sheeran", year:2017},
    {title:"Beautiful People", artist:"Ed Sheeran", year:2019},
    {title:"Antisocial", artist:"Ed Sheeran", year:2019},

    // More Ariana Grande
    {title:"Break Free", artist:"Ariana Grande", year:2014},
    {title:"One Last Time", artist:"Ariana Grande", year:2013},
    {title:"Dangerous Woman", artist:"Ariana Grande", year:2016},
    {title:"breathin", artist:"Ariana Grande", year:2018},
    {title:"Rain on Me", artist:"Lady Gaga", year:2020},
    {title:"34+35", artist:"Ariana Grande", year:2020},
    {title:"Santa Tell Me", artist:"Ariana Grande", year:2014},

    // More Drake
    {title:"Started From the Bottom", artist:"Drake", year:2013},
    {title:"Hold On, We're Going Home", artist:"Drake", year:2013},
    {title:"Take Care", artist:"Drake", year:2011},
    {title:"Passionfruit", artist:"Drake", year:2017},
    {title:"Controlla", artist:"Drake", year:2016},
    {title:"Know Yourself", artist:"Drake", year:2015},
    {title:"Toosie Slide", artist:"Drake", year:2020},
    {title:"Laugh Now Cry Later", artist:"Drake", year:2020},

    // More Post Malone
    {title:"White Iverson", artist:"Post Malone", year:2015},
    {title:"Wow.", artist:"Post Malone", year:2019},
    {title:"I Fall Apart", artist:"Post Malone", year:2016},
    {title:"Goodbyes", artist:"Post Malone", year:2019},
    {title:"Take What You Want", artist:"Post Malone", year:2019},

    // More Eminem / Kanye / Kendrick
    {title:"Stan", artist:"Eminem", year:2000},
    {title:"Not Afraid", artist:"Eminem", year:2010},
    {title:"Love the Way You Lie", artist:"Eminem", year:2010},
    {title:"Rap God", artist:"Eminem", year:2013},
    {title:"Power", artist:"Kanye West", year:2010},
    {title:"Runaway", artist:"Kanye West", year:2010},
    {title:"All Falls Down", artist:"Kanye West", year:2004},
    {title:"Flashing Lights", artist:"Kanye West", year:2007},
    {title:"Famous", artist:"Kanye West", year:2016},
    {title:"Alright", artist:"Kendrick Lamar", year:2015},
    {title:"Bitch Don't Kill My Vibe", artist:"Kendrick Lamar", year:2012},
    {title:"Swimming Pools (Drank)", artist:"Kendrick Lamar", year:2012},
    {title:"money trees", artist:"Kendrick Lamar", year:2012},
    {title:"loyalty.", artist:"Kendrick Lamar", year:2017},

    // Doja Cat / SZA / Juice WRLD / Pop Smoke
    {title:"Say So", artist:"Doja Cat", year:2019},
    {title:"Kiss Me More", artist:"Doja Cat", year:2021},
    {title:"Streets", artist:"Doja Cat", year:2019},
    {title:"Woman", artist:"Doja Cat", year:2021},
    {title:"Vegas", artist:"Doja Cat", year:2022},
    {title:"Good Days", artist:"SZA", year:2020},
    {title:"Love Galore", artist:"SZA", year:2017},
    {title:"Drew Barrymore", artist:"SZA", year:2017},
    {title:"Lucid Dreams", artist:"Juice WRLD", year:2018},
    {title:"All Girls Are the Same", artist:"Juice WRLD", year:2018},
    {title:"Legends", artist:"Juice WRLD", year:2018},
    {title:"Righteous", artist:"Juice WRLD", year:2020},
    {title:"SAD!", artist:"XXXTentacion", year:2018},
    {title:"Moonlight", artist:"XXXTentacion", year:2018},
    {title:"Jocelyn Flores", artist:"XXXTentacion", year:2017},
    {title:"changes", artist:"XXXTentacion", year:2017},
    {title:"Dior", artist:"Pop Smoke", year:2019},
    {title:"Welcome to the Party", artist:"Pop Smoke", year:2018},
    {title:"What You Know Bout Love", artist:"Pop Smoke", year:2020},
    {title:"The Box", artist:"Roddy Ricch", year:2019},
    {title:"High Fashion", artist:"Roddy Ricch", year:2020},
    {title:"Drip Too Hard", artist:"Lil Baby", year:2018},
    {title:"Woah", artist:"Lil Baby", year:2019},
    {title:"We Paid", artist:"Lil Baby", year:2020},
    {title:"Mask Off", artist:"Future", year:2017},
    {title:"Low Life", artist:"Future", year:2016},
    {title:"Jumpman", artist:"Drake", year:2015},
    {title:"Super Bass", artist:"Nicki Minaj", year:2011},
    {title:"Anaconda", artist:"Nicki Minaj", year:2014},
    {title:"Starships", artist:"Nicki Minaj", year:2012},
    {title:"Moment 4 Life", artist:"Nicki Minaj", year:2010},
    {title:"XO Tour Llif3", artist:"Lil Uzi Vert", year:2017},
    {title:"Just Wanna Rock", artist:"Lil Uzi Vert", year:2022},
    {title:"Redbone", artist:"Childish Gambino", year:2016},
    {title:"This Is America", artist:"Childish Gambino", year:2018},
    {title:"Rapstar", artist:"Polo G", year:2021},

    // Rock / Alternative
    {title:"In The End", artist:"Linkin Park", year:2000},
    {title:"Numb", artist:"Linkin Park", year:2003},
    {title:"Crawling", artist:"Linkin Park", year:2000},
    {title:"What I've Done", artist:"Linkin Park", year:2007},
    {title:"Somewhere I Belong", artist:"Linkin Park", year:2003},
    {title:"Faint", artist:"Linkin Park", year:2003},
    {title:"Breaking the Habit", artist:"Linkin Park", year:2004},
    {title:"New Divide", artist:"Linkin Park", year:2009},
    {title:"Boulevard of Broken Dreams", artist:"Green Day", year:2004},
    {title:"American Idiot", artist:"Green Day", year:2004},
    {title:"Wake Me Up When September Ends", artist:"Green Day", year:2004},
    {title:"Basket Case", artist:"Green Day", year:1994},
    {title:"Good Riddance (Time of Your Life)", artist:"Green Day", year:1997},
    {title:"Holiday", artist:"Green Day", year:2004},
    {title:"Everlong", artist:"Foo Fighters", year:1997},
    {title:"Best of You", artist:"Foo Fighters", year:2005},
    {title:"The Pretender", artist:"Foo Fighters", year:2007},
    {title:"Learn to Fly", artist:"Foo Fighters", year:1999},
    {title:"Walk", artist:"Foo Fighters", year:2011},
    {title:"All My Life", artist:"Foo Fighters", year:2002},
    {title:"Misery Business", artist:"Paramore", year:2007},
    {title:"The Only Exception", artist:"Paramore", year:2009},
    {title:"Still Into You", artist:"Paramore", year:2012},
    {title:"Ain't It Fun", artist:"Paramore", year:2013},
    {title:"Decode", artist:"Paramore", year:2008},
    {title:"Sugar, We're Goin Down", artist:"Fall Out Boy", year:2005},
    {title:"Dance Dance", artist:"Fall Out Boy", year:2005},
    {title:"Thnks fr th Mmrs", artist:"Fall Out Boy", year:2007},
    {title:"My Songs Know What You Did in the Dark", artist:"Fall Out Boy", year:2013},
    {title:"Centuries", artist:"Fall Out Boy", year:2014},
    {title:"Uma Thurman", artist:"Fall Out Boy", year:2015},
    {title:"Welcome to the Black Parade", artist:"My Chemical Romance", year:2006},
    {title:"I'm Not Okay (I Promise)", artist:"My Chemical Romance", year:2004},
    {title:"Famous Last Words", artist:"My Chemical Romance", year:2006},
    {title:"Helena", artist:"My Chemical Romance", year:2004},
    {title:"Teenagers", artist:"My Chemical Romance", year:2006},
    {title:"Do I Wanna Know?", artist:"Arctic Monkeys", year:2013},
    {title:"R U Mine?", artist:"Arctic Monkeys", year:2013},
    {title:"Fluorescent Adolescent", artist:"Arctic Monkeys", year:2011},
    {title:"505", artist:"Arctic Monkeys", year:2007},
    {title:"Why'd You Only Call Me When You're High?", artist:"Arctic Monkeys", year:2013},
    {title:"Snap Out of It", artist:"Arctic Monkeys", year:2013},
    {title:"I Bet You Look Good on the Dancefloor", artist:"Arctic Monkeys", year:2005},
    {title:"Mr. Brightside", artist:"The Killers", year:2003},
    {title:"Somebody Told Me", artist:"The Killers", year:2004},
    {title:"All These Things That I've Done", artist:"The Killers", year:2004},
    {title:"Human", artist:"The Killers", year:2008},
    {title:"Smile Like You Mean It", artist:"The Killers", year:2004},
    {title:"Chocolate", artist:"The 1975", year:2013},
    {title:"Sex", artist:"The 1975", year:2013},
    {title:"The Sound", artist:"The 1975", year:2016},
    {title:"Love Me", artist:"The 1975", year:2016},
    {title:"Somebody Else", artist:"The 1975", year:2016},
    {title:"If You're Too Shy (Let Me Know)", artist:"The 1975", year:2020},
    {title:"Yellow", artist:"Coldplay", year:2000},
    {title:"The Scientist", artist:"Coldplay", year:2002},
    {title:"Fix You", artist:"Coldplay", year:2005},
    {title:"Viva la Vida", artist:"Coldplay", year:2008},
    {title:"Speed of Sound", artist:"Coldplay", year:2005},
    {title:"Clocks", artist:"Coldplay", year:2002},
    {title:"A Sky Full of Stars", artist:"Coldplay", year:2014},
    {title:"Adventure of a Lifetime", artist:"Coldplay", year:2015},
    {title:"Higher Power", artist:"Coldplay", year:2021},
    {title:"Madness", artist:"Muse", year:2012},
    {title:"Uprising", artist:"Muse", year:2009},
    {title:"Supermassive Black Hole", artist:"Muse", year:2006},
    {title:"Starlight", artist:"Muse", year:2006},
    {title:"Time Is Running Out", artist:"Muse", year:2003},
    {title:"Rehab", artist:"Amy Winehouse", year:2006},
    {title:"Back to Black", artist:"Amy Winehouse", year:2006},
    {title:"Valerie", artist:"Amy Winehouse", year:2007},
    {title:"Tears Dry on Their Own", artist:"Amy Winehouse", year:2007},
    {title:"Take Me to Church", artist:"Hozier", year:2013},
    {title:"Work Song", artist:"Hozier", year:2014},
    {title:"Lights", artist:"Ellie Goulding", year:2010},
    {title:"Burn", artist:"Ellie Goulding", year:2013},
    {title:"Love Me Like You Do", artist:"Ellie Goulding", year:2015},
    {title:"On My Mind", artist:"Ellie Goulding", year:2015},
    {title:"Video Games", artist:"Lana Del Rey", year:2011},
    {title:"Summertime Sadness", artist:"Lana Del Rey", year:2012},
    {title:"Young and Beautiful", artist:"Lana Del Rey", year:2013},
    {title:"Born to Die", artist:"Lana Del Rey", year:2012},
    {title:"The Less I Know the Better", artist:"Tame Impala", year:2015},
    {title:"Let It Happen", artist:"Tame Impala", year:2015},
    {title:"Elephant", artist:"Tame Impala", year:2012},
    {title:"Lost in Yesterday", artist:"Tame Impala", year:2020},
    {title:"Thinkin Bout You", artist:"Frank Ocean", year:2012},
    {title:"Super Rich Kids", artist:"Frank Ocean", year:2012},
    {title:"Swim Good", artist:"Frank Ocean", year:2011},
    {title:"Let Her Go", artist:"Passenger", year:2012},
    {title:"Say You Won't Let Go", artist:"James Arthur", year:2016},

    // Electronic / Dance
    {title:"Closer", artist:"The Chainsmokers", year:2016},
    {title:"Don't Let Me Down", artist:"The Chainsmokers", year:2016},
    {title:"Something Just Like This", artist:"The Chainsmokers", year:2017},
    {title:"Paris", artist:"The Chainsmokers", year:2017},
    {title:"Roses", artist:"The Chainsmokers", year:2015},
    {title:"Happier", artist:"Marshmello", year:2018},
    {title:"Friends", artist:"Marshmello", year:2018},
    {title:"Silence", artist:"Marshmello", year:2017},
    {title:"Alone", artist:"Marshmello", year:2016},
    {title:"Summer", artist:"Calvin Harris", year:2014},
    {title:"Feel So Close", artist:"Calvin Harris", year:2011},
    {title:"Outside", artist:"Calvin Harris", year:2014},
    {title:"How Deep Is Your Love", artist:"Calvin Harris", year:2015},
    {title:"This Is What You Came For", artist:"Calvin Harris", year:2016},
    {title:"Promises", artist:"Calvin Harris", year:2018},
    {title:"Faking It", artist:"Calvin Harris", year:2017},
    {title:"Chandelier", artist:"Sia", year:2014},
    {title:"Cheap Thrills", artist:"Sia", year:2016},
    {title:"Elastic Heart", artist:"Sia", year:2015},
    {title:"Unstoppable", artist:"Sia", year:2016},
    {title:"The Greatest", artist:"Sia", year:2016},
    {title:"Taki Taki", artist:"DJ Snake", year:2018},
    {title:"Turn Down for What", artist:"DJ Snake", year:2013},
    {title:"Let Me Love You", artist:"DJ Snake", year:2016},
    {title:"Middle", artist:"DJ Snake", year:2016},
    {title:"Where Dem Girls At", artist:"David Guetta", year:2011},
    {title:"Hey Mama", artist:"David Guetta", year:2015},
    {title:"Addicted to You", artist:"Avicii", year:2013},
    {title:"Silhouettes", artist:"Avicii", year:2012},
    {title:"I Could Be the One", artist:"Avicii", year:2012},
    {title:"SOS", artist:"Avicii", year:2019},

    // Classic Rock / Legends
    {title:"Stairway to Heaven", artist:"Led Zeppelin", year:1971},
    {title:"Whole Lotta Love", artist:"Led Zeppelin", year:1969},
    {title:"Kashmir", artist:"Led Zeppelin", year:1975},
    {title:"Black Dog", artist:"Led Zeppelin", year:1971},
    {title:"Immigrant Song", artist:"Led Zeppelin", year:1970},
    {title:"Another Brick in the Wall", artist:"Pink Floyd", year:1979},
    {title:"Comfortably Numb", artist:"Pink Floyd", year:1979},
    {title:"Wish You Were Here", artist:"Pink Floyd", year:1975},
    {title:"Hey Jude", artist:"The Beatles", year:1968},
    {title:"Let It Be", artist:"The Beatles", year:1970},
    {title:"Come Together", artist:"The Beatles", year:1969},
    {title:"Yesterday", artist:"The Beatles", year:1965},
    {title:"Here Comes the Sun", artist:"The Beatles", year:1969},
    {title:"Twist and Shout", artist:"The Beatles", year:1963},
    {title:"Help!", artist:"The Beatles", year:1965},
    {title:"Something", artist:"The Beatles", year:1969},
    {title:"(I Can't Get No) Satisfaction", artist:"The Rolling Stones", year:1965},
    {title:"Paint It Black", artist:"The Rolling Stones", year:1966},
    {title:"Sympathy for the Devil", artist:"The Rolling Stones", year:1968},
    {title:"Wild Horses", artist:"The Rolling Stones", year:1971},
    {title:"Start Me Up", artist:"The Rolling Stones", year:1981},
    {title:"Hotel California", artist:"Eagles", year:1977},
    {title:"Take It Easy", artist:"Eagles", year:1972},
    {title:"Desperado", artist:"Eagles", year:1973},
    {title:"Back in Black", artist:"AC/DC", year:1980},
    {title:"Highway to Hell", artist:"AC/DC", year:1979},
    {title:"Thunderstruck", artist:"AC/DC", year:1990},
    {title:"You Shook Me All Night Long", artist:"AC/DC", year:1980},
    {title:"Enter Sandman", artist:"Metallica", year:1991},
    {title:"Nothing Else Matters", artist:"Metallica", year:1991},
    {title:"The Unforgiven", artist:"Metallica", year:1991},
    {title:"Master of Puppets", artist:"Metallica", year:1986},
    {title:"One", artist:"Metallica", year:1988},
    {title:"Welcome to the Jungle", artist:"Guns N' Roses", year:1987},
    {title:"Paradise City", artist:"Guns N' Roses", year:1987},
    {title:"Patience", artist:"Guns N' Roses", year:1989},
    {title:"I Don't Want to Miss a Thing", artist:"Aerosmith", year:1998},
    {title:"Dream On", artist:"Aerosmith", year:1973},
    {title:"Sweet Emotion", artist:"Aerosmith", year:1975},

    // Legends
    {title:"Purple Rain", artist:"Prince", year:1984},
    {title:"Kiss", artist:"Prince", year:1986},
    {title:"When Doves Cry", artist:"Prince", year:1984},
    {title:"Little Red Corvette", artist:"Prince", year:1982},
    {title:"Raspberry Beret", artist:"Prince", year:1985},
    {title:"Let's Go Crazy", artist:"Prince", year:1984},
    {title:"Heroes", artist:"David Bowie", year:1977},
    {title:"Let's Dance", artist:"David Bowie", year:1983},
    {title:"Space Oddity", artist:"David Bowie", year:1969},
    {title:"Life on Mars?", artist:"David Bowie", year:1971},
    {title:"Ziggy Stardust", artist:"David Bowie", year:1972},
    {title:"Modern Love", artist:"David Bowie", year:1983},
    {title:"Rocket Man", artist:"Elton John", year:1972},
    {title:"Tiny Dancer", artist:"Elton John", year:1971},
    {title:"Crocodile Rock", artist:"Elton John", year:1972},
    {title:"Your Song", artist:"Elton John", year:1970},
    {title:"I'm Still Standing", artist:"Elton John", year:1983},
    {title:"Candle in the Wind", artist:"Elton John", year:1973},
    {title:"Bennie and the Jets", artist:"Elton John", year:1973},
    {title:"Goodbye Yellow Brick Road", artist:"Elton John", year:1973},
    {title:"In the Air Tonight", artist:"Phil Collins", year:1981},
    {title:"Against All Odds", artist:"Phil Collins", year:1984},
    {title:"Another Day in Paradise", artist:"Phil Collins", year:1989},
    {title:"You Can't Hurry Love", artist:"Phil Collins", year:1983},
    {title:"Sussudio", artist:"Phil Collins", year:1985},
    {title:"Born to Run", artist:"Bruce Springsteen", year:1975},
    {title:"Dancing in the Dark", artist:"Bruce Springsteen", year:1984},
    {title:"Born in the USA", artist:"Bruce Springsteen", year:1984},
    {title:"I Will Always Love You", artist:"Whitney Houston", year:1992},
    {title:"I Wanna Dance with Somebody", artist:"Whitney Houston", year:1987},
    {title:"Greatest Love of All", artist:"Whitney Houston", year:1986},
    {title:"How Will I Know", artist:"Whitney Houston", year:1985},
    {title:"All I Want for Christmas Is You", artist:"Mariah Carey", year:1994},
    {title:"We Belong Together", artist:"Mariah Carey", year:2005},
    {title:"Hero", artist:"Mariah Carey", year:1993},
    {title:"Fantasy", artist:"Mariah Carey", year:1995},
    {title:"Say My Name", artist:"Destiny's Child", year:1999},
    {title:"Survivor", artist:"Destiny's Child", year:2001},
    {title:"Bootylicious", artist:"Destiny's Child", year:2001},
    {title:"Bills, Bills, Bills", artist:"Destiny's Child", year:1999},
    {title:"Dancing Queen", artist:"ABBA", year:1976},
    {title:"Waterloo", artist:"ABBA", year:1974},
    {title:"Mamma Mia", artist:"ABBA", year:1975},
    {title:"Fernando", artist:"ABBA", year:1976},
    {title:"The Winner Takes It All", artist:"ABBA", year:1980},
    {title:"Gimme! Gimme! Gimme!", artist:"ABBA", year:1979},
    {title:"Superstition", artist:"Stevie Wonder", year:1972},
    {title:"Sir Duke", artist:"Stevie Wonder", year:1977},
    {title:"I Just Called to Say I Love You", artist:"Stevie Wonder", year:1984},
    {title:"Isn't She Lovely", artist:"Stevie Wonder", year:1976},
    {title:"Respect", artist:"Aretha Franklin", year:1967},
    {title:"Think", artist:"Aretha Franklin", year:1968},
    {title:"I Say a Little Prayer", artist:"Aretha Franklin", year:1968},
    {title:"Jailhouse Rock", artist:"Elvis Presley", year:1957},
    {title:"Suspicious Minds", artist:"Elvis Presley", year:1969},
    {title:"Can't Help Falling in Love", artist:"Elvis Presley", year:1961},
    {title:"Hound Dog", artist:"Elvis Presley", year:1956},
    {title:"My Way", artist:"Frank Sinatra", year:1969},
    {title:"Fly Me to the Moon", artist:"Frank Sinatra", year:1964},
    {title:"New York, New York", artist:"Frank Sinatra", year:1980},
    {title:"September", artist:"Earth, Wind & Fire", year:1978},
    {title:"Boogie Wonderland", artist:"Earth, Wind & Fire", year:1979},
    {title:"Hot Stuff", artist:"Donna Summer", year:1979},
    {title:"I Feel Love", artist:"Donna Summer", year:1977},

    // R&B / Soul
    {title:"No One", artist:"Alicia Keys", year:2007},
    {title:"Fallin'", artist:"Alicia Keys", year:2001},
    {title:"Girl on Fire", artist:"Alicia Keys", year:2012},
    {title:"If I Ain't Got You", artist:"Alicia Keys", year:2003},
    {title:"Empire State of Mind", artist:"Jay-Z", year:2009},
    {title:"99 Problems", artist:"Jay-Z", year:2004},
    {title:"Run This Town", artist:"Jay-Z", year:2009},
    {title:"All of Me", artist:"John Legend", year:2013},
    {title:"Ordinary People", artist:"John Legend", year:2004},
    {title:"So Sick", artist:"Ne-Yo", year:2006},
    {title:"Because of You", artist:"Ne-Yo", year:2007},
    {title:"Miss Independent", artist:"Ne-Yo", year:2008},
    {title:"With You", artist:"Chris Brown", year:2007},
    {title:"Forever", artist:"Chris Brown", year:2008},
    {title:"Fine China", artist:"Chris Brown", year:2013},
    {title:"Heartbreak Anniversary", artist:"Giveon", year:2020},
    {title:"Formation", artist:"Beyonce", year:2016},
    {title:"Love on Top", artist:"Beyonce", year:2011},

    // More pop / 2000s–2010s
    {title:"I Gotta Feeling", artist:"Black Eyed Peas", year:2009},
    {title:"Boom Boom Pow", artist:"Black Eyed Peas", year:2009},
    {title:"Where Is the Love", artist:"Black Eyed Peas", year:2003},
    {title:"Just Can't Get Enough", artist:"Black Eyed Peas", year:2011},
    {title:"Hot in Herre", artist:"Nelly", year:2002},
    {title:"Dilemma", artist:"Nelly", year:2002},
    {title:"Right Round", artist:"Flo Rida", year:2009},
    {title:"Good Feeling", artist:"Flo Rida", year:2011},
    {title:"Whistle", artist:"Flo Rida", year:2012},
    {title:"Tik Tok", artist:"Kesha", year:2009},
    {title:"We R Who We R", artist:"Kesha", year:2010},
    {title:"Die Young", artist:"Kesha", year:2012},
    {title:"Give Me Everything", artist:"Pitbull", year:2011},
    {title:"International Love", artist:"Pitbull", year:2012},
    {title:"Timber", artist:"Pitbull", year:2013},
    {title:"So What", artist:"Pink", year:2008},
    {title:"Just Give Me a Reason", artist:"Pink", year:2012},
    {title:"What About Us", artist:"Pink", year:2017},
    {title:"Raise Your Glass", artist:"Pink", year:2010},
    {title:"Try", artist:"Pink", year:2012},
    {title:"Wiggle", artist:"Jason Derulo", year:2014},
    {title:"Want to Want Me", artist:"Jason Derulo", year:2015},
    {title:"Talk Dirty", artist:"Jason Derulo", year:2013},
    {title:"Baby", artist:"Justin Bieber", year:2010},
    {title:"Boyfriend", artist:"Justin Bieber", year:2012},
    {title:"Ghost", artist:"Justin Bieber", year:2021},
    {title:"Treat You Better", artist:"Shawn Mendes", year:2016},
    {title:"In My Blood", artist:"Shawn Mendes", year:2018},
    {title:"Wonder", artist:"Shawn Mendes", year:2020},
    {title:"Don't Go Yet", artist:"Camila Cabello", year:2021},
    {title:"Crying in the Club", artist:"Camila Cabello", year:2017},

    // Latin
    {title:"Dakiti", artist:"Bad Bunny", year:2020},
    {title:"Titi Me Pregunto", artist:"Bad Bunny", year:2022},
    {title:"Me Porto Bonito", artist:"Bad Bunny", year:2022},
    {title:"Yonaguni", artist:"Bad Bunny", year:2021},
    {title:"MIA", artist:"Bad Bunny", year:2018},
    {title:"Hips Don't Lie", artist:"Shakira", year:2006},
    {title:"Waka Waka (This Time for Africa)", artist:"Shakira", year:2010},
    {title:"Whenever, Wherever", artist:"Shakira", year:2001},
    {title:"She Wolf", artist:"Shakira", year:2009},
    {title:"Gasolina", artist:"Daddy Yankee", year:2004},
    {title:"Mi Gente", artist:"J Balvin", year:2017},
    {title:"Safari", artist:"J Balvin", year:2016},
    {title:"Hawái", artist:"Maluma", year:2020},
    {title:"Felices los 4", artist:"Maluma", year:2017},

    // K-Pop
    {title:"Boy With Luv", artist:"BTS", year:2019},
    {title:"DNA", artist:"BTS", year:2017},
    {title:"Fake Love", artist:"BTS", year:2018},
    {title:"Spring Day", artist:"BTS", year:2017},
    {title:"Life Goes On", artist:"BTS", year:2020},
    {title:"ON", artist:"BTS", year:2020},
    {title:"Mic Drop", artist:"BTS", year:2017},
    {title:"How You Like That", artist:"BLACKPINK", year:2020},
    {title:"Lovesick Girls", artist:"BLACKPINK", year:2020},
    {title:"Pink Venom", artist:"BLACKPINK", year:2022},
    {title:"Ddu-Du Ddu-Du", artist:"BLACKPINK", year:2018},
    {title:"Ice Cream", artist:"BLACKPINK", year:2020},

    // UK
    {title:"Doja", artist:"Central Cee", year:2021},
    {title:"Loading", artist:"Central Cee", year:2021},
    {title:"Day in the Life", artist:"Central Cee", year:2022},
    {title:"Funky Friday", artist:"Dave", year:2018},
    {title:"Location", artist:"Dave", year:2019},
    {title:"Ladbroke Grove", artist:"AJ Tracey", year:2019},
    {title:"Wifey Riddim", artist:"AJ Tracey", year:2019},
    {title:"Rain", artist:"Aitch", year:2021},
    {title:"Ray Bands", artist:"Aitch", year:2020},
];
