// ============================================
// EARLOCK — DATA FILE
// 10 genre categories, 100+ songs each.
// Format: {title, artist, year}
// Append new entries at the end of each genre's songs array.
// ============================================

const GENRES = {

  pop: {label:"Pop", songs:[
    {title:"Blinding Lights", artist:"The Weeknd", year:2019},
    {title:"Shape of You", artist:"Ed Sheeran", year:2017},
    {title:"Dance Monkey", artist:"Tones and I", year:2019},
    {title:"Stay", artist:"The Kid LAROI", year:2021},
    {title:"Levitating", artist:"Dua Lipa", year:2020},
    {title:"drivers license", artist:"Olivia Rodrigo", year:2021},
    {title:"Watermelon Sugar", artist:"Harry Styles", year:2019},
    {title:"good 4 u", artist:"Olivia Rodrigo", year:2021},
    {title:"Heat Waves", artist:"Glass Animals", year:2020},
    {title:"Easy On Me", artist:"Adele", year:2021},
    {title:"As It Was", artist:"Harry Styles", year:2022},
    {title:"Anti-Hero", artist:"Taylor Swift", year:2022},
    {title:"Flowers", artist:"Miley Cyrus", year:2023},
    {title:"Cruel Summer", artist:"Taylor Swift", year:2019},
    {title:"Golden Hour", artist:"JVKE", year:2022},
    {title:"Unholy", artist:"Sam Smith", year:2022},
    {title:"abcdefu", artist:"GAYLE", year:2021},
    {title:"Save Your Tears", artist:"The Weeknd", year:2021},
    {title:"Bad Guy", artist:"Billie Eilish", year:2019},
    {title:"Positions", artist:"Ariana Grande", year:2020},
    {title:"Peaches", artist:"Justin Bieber", year:2021},
    {title:"About Damn Time", artist:"Lizzo", year:2022},
    {title:"Late Night Talking", artist:"Harry Styles", year:2022},
    {title:"Lavender Haze", artist:"Taylor Swift", year:2022},
    {title:"Karma", artist:"Taylor Swift", year:2022},
    {title:"Shake It Off", artist:"Taylor Swift", year:2014},
    {title:"Blank Space", artist:"Taylor Swift", year:2014},
    {title:"Style", artist:"Taylor Swift", year:2014},
    {title:"Love Story", artist:"Taylor Swift", year:2008},
    {title:"Cardigan", artist:"Taylor Swift", year:2020},
    {title:"You Belong With Me", artist:"Taylor Swift", year:2009},
    {title:"All Too Well", artist:"Taylor Swift", year:2012},
    {title:"22", artist:"Taylor Swift", year:2012},
    {title:"Starboy", artist:"The Weeknd", year:2016},
    {title:"Can't Feel My Face", artist:"The Weeknd", year:2015},
    {title:"I Feel It Coming", artist:"The Weeknd", year:2016},
    {title:"popular", artist:"The Weeknd", year:2023},
    {title:"Rolling in the Deep", artist:"Adele", year:2010},
    {title:"Someone Like You", artist:"Adele", year:2011},
    {title:"Hello", artist:"Adele", year:2015},
    {title:"Uptown Funk", artist:"Mark Ronson", year:2014},
    {title:"Happy", artist:"Pharrell Williams", year:2013},
    {title:"Thinking Out Loud", artist:"Ed Sheeran", year:2014},
    {title:"Perfect", artist:"Ed Sheeran", year:2017},
    {title:"Bad Habits", artist:"Ed Sheeran", year:2021},
    {title:"Shivers", artist:"Ed Sheeran", year:2021},
    {title:"Castle On The Hill", artist:"Ed Sheeran", year:2017},
    {title:"Sorry", artist:"Justin Bieber", year:2015},
    {title:"Love Yourself", artist:"Justin Bieber", year:2015},
    {title:"Ghost", artist:"Justin Bieber", year:2021},
    {title:"Baby", artist:"Justin Bieber", year:2010},
    {title:"Havana", artist:"Camila Cabello", year:2017},
    {title:"New Rules", artist:"Dua Lipa", year:2017},
    {title:"One Kiss", artist:"Dua Lipa", year:2018},
    {title:"Physical", artist:"Dua Lipa", year:2020},
    {title:"Don't Start Now", artist:"Dua Lipa", year:2019},
    {title:"Senorita", artist:"Shawn Mendes", year:2019},
    {title:"Treat You Better", artist:"Shawn Mendes", year:2016},
    {title:"In My Blood", artist:"Shawn Mendes", year:2018},
    {title:"7 Years", artist:"Lukas Graham", year:2015},
    {title:"Stressed Out", artist:"Twenty One Pilots", year:2015},
    {title:"Heathens", artist:"Twenty One Pilots", year:2016},
    {title:"Sugar", artist:"Maroon 5", year:2014},
    {title:"Girls Like You", artist:"Maroon 5", year:2018},
    {title:"Moves Like Jagger", artist:"Maroon 5", year:2011},
    {title:"Wrecking Ball", artist:"Miley Cyrus", year:2013},
    {title:"Problem", artist:"Ariana Grande", year:2014},
    {title:"Thank U Next", artist:"Ariana Grande", year:2018},
    {title:"7 Rings", artist:"Ariana Grande", year:2019},
    {title:"No Tears Left To Cry", artist:"Ariana Grande", year:2018},
    {title:"Into You", artist:"Ariana Grande", year:2016},
    {title:"breathin", artist:"Ariana Grande", year:2018},
    {title:"34+35", artist:"Ariana Grande", year:2020},
    {title:"happier than ever", artist:"Billie Eilish", year:2021},
    {title:"brutal", artist:"Olivia Rodrigo", year:2021},
    {title:"traitor", artist:"Olivia Rodrigo", year:2021},
    {title:"vampire", artist:"Olivia Rodrigo", year:2023},
    {title:"get him back!", artist:"Olivia Rodrigo", year:2023},
    {title:"What Was I Made For", artist:"Billie Eilish", year:2023},
    {title:"Ocean Eyes", artist:"Billie Eilish", year:2016},
    {title:"We Are Never Ever Getting Back Together", artist:"Taylor Swift", year:2012},
    {title:"Adore You", artist:"Harry Styles", year:2019},
    {title:"Falling", artist:"Harry Styles", year:2019},
    {title:"Sign of the Times", artist:"Harry Styles", year:2017},
    {title:"We Don't Talk Anymore", artist:"Charlie Puth", year:2016},
    {title:"Attention", artist:"Charlie Puth", year:2017},
    {title:"Someone You Loved", artist:"Lewis Capaldi", year:2018},
    {title:"Before You Go", artist:"Lewis Capaldi", year:2019},
    {title:"Young Dumb & Broke", artist:"Khalid", year:2017},
    {title:"Without Me", artist:"Halsey", year:2018},
    {title:"Bad at Love", artist:"Halsey", year:2017},
    {title:"Just The Way You Are", artist:"Bruno Mars", year:2010},
    {title:"Locked Out of Heaven", artist:"Bruno Mars", year:2012},
    {title:"24K Magic", artist:"Bruno Mars", year:2016},
    {title:"That's What I Like", artist:"Bruno Mars", year:2016},
    {title:"Stay With Me", artist:"Sam Smith", year:2014},
    {title:"Chandelier", artist:"Sia", year:2014},
    {title:"Cheap Thrills", artist:"Sia", year:2016},
    {title:"Unstoppable", artist:"Sia", year:2016},
    {title:"Say So", artist:"Doja Cat", year:2019},
    {title:"Kiss Me More", artist:"Doja Cat", year:2021},
    {title:"Need To Know", artist:"Doja Cat", year:2021},
    {title:"Something Just Like This", artist:"The Chainsmokers", year:2017},
    {title:"We Don't Talk About Bruno", artist:"Carolina Gaitan", year:2021},
    {title:"Royals", artist:"Lorde", year:2013},
    {title:"Green Light", artist:"Lorde", year:2017},
    {title:"Beggin", artist:"Maneskin", year:2021},
    {title:"Escapism", artist:"RAYE", year:2022},
    {title:"Kill Bill", artist:"SZA", year:2022},
    {title:"Mood", artist:"24kGoldn", year:2020},
    {title:"Astronaut In The Ocean", artist:"Masked Wolf", year:2021},
    {title:"Cool", artist:"Dua Lipa", year:2020},
    {title:"Midnight Rain", artist:"Taylor Swift", year:2022},
    {title:"willow", artist:"Taylor Swift", year:2020},
    {title:"Enchanted", artist:"Taylor Swift", year:2010},
    {title:"I Knew You Were Trouble", artist:"Taylor Swift", year:2012},
    {title:"Lover", artist:"Taylor Swift", year:2019},
    {title:"Me!", artist:"Taylor Swift", year:2019},
  ]},

  hiphop: {label:"Hip-Hop / Rap", songs:[
    {title:"Sicko Mode", artist:"Travis Scott", year:2018},
    {title:"Goosebumps", artist:"Travis Scott", year:2016},
    {title:"Antidote", artist:"Travis Scott", year:2015},
    {title:"HIGHEST IN THE ROOM", artist:"Travis Scott", year:2019},
    {title:"Franchise", artist:"Travis Scott", year:2020},
    {title:"DNA", artist:"Kendrick Lamar", year:2017},
    {title:"HUMBLE", artist:"Kendrick Lamar", year:2017},
    {title:"Not Like Us", artist:"Kendrick Lamar", year:2024},
    {title:"All The Stars", artist:"Kendrick Lamar", year:2018},
    {title:"Alright", artist:"Kendrick Lamar", year:2015},
    {title:"Bitch Don't Kill My Vibe", artist:"Kendrick Lamar", year:2012},
    {title:"Swimming Pools (Drank)", artist:"Kendrick Lamar", year:2012},
    {title:"money trees", artist:"Kendrick Lamar", year:2012},
    {title:"loyalty.", artist:"Kendrick Lamar", year:2017},
    {title:"Savage", artist:"Megan Thee Stallion", year:2020},
    {title:"WAP", artist:"Cardi B", year:2020},
    {title:"Bodak Yellow", artist:"Cardi B", year:2017},
    {title:"I Like It", artist:"Cardi B", year:2018},
    {title:"Rockstar", artist:"DaBaby", year:2020},
    {title:"BOP", artist:"DaBaby", year:2019},
    {title:"MIDDLE CHILD", artist:"J. Cole", year:2019},
    {title:"No Role Modelz", artist:"J. Cole", year:2014},
    {title:"Love Yourz", artist:"J. Cole", year:2014},
    {title:"Apparently", artist:"J. Cole", year:2014},
    {title:"In Da Club", artist:"50 Cent", year:2003},
    {title:"Gold Digger", artist:"Kanye West", year:2005},
    {title:"Stronger", artist:"Kanye West", year:2007},
    {title:"Heartless", artist:"Kanye West", year:2008},
    {title:"Power", artist:"Kanye West", year:2010},
    {title:"Runaway", artist:"Kanye West", year:2010},
    {title:"All Falls Down", artist:"Kanye West", year:2004},
    {title:"Flashing Lights", artist:"Kanye West", year:2007},
    {title:"Famous", artist:"Kanye West", year:2016},
    {title:"Lose Yourself", artist:"Eminem", year:2002},
    {title:"Without Me", artist:"Eminem", year:2002},
    {title:"The Real Slim Shady", artist:"Eminem", year:2000},
    {title:"Stan", artist:"Eminem", year:2000},
    {title:"Not Afraid", artist:"Eminem", year:2010},
    {title:"Rap God", artist:"Eminem", year:2013},
    {title:"Love the Way You Lie", artist:"Eminem", year:2010},
    {title:"One Dance", artist:"Drake", year:2016},
    {title:"God's Plan", artist:"Drake", year:2018},
    {title:"In My Feelings", artist:"Drake", year:2018},
    {title:"Nice For What", artist:"Drake", year:2018},
    {title:"Hotline Bling", artist:"Drake", year:2015},
    {title:"Rich Flex", artist:"Drake", year:2022},
    {title:"Knife Talk", artist:"Drake", year:2021},
    {title:"Started From the Bottom", artist:"Drake", year:2013},
    {title:"Take Care", artist:"Drake", year:2011},
    {title:"Passionfruit", artist:"Drake", year:2017},
    {title:"Toosie Slide", artist:"Drake", year:2020},
    {title:"Laugh Now Cry Later", artist:"Drake", year:2020},
    {title:"Jumpman", artist:"Drake", year:2015},
    {title:"Hold On, We're Going Home", artist:"Drake", year:2013},
    {title:"Know Yourself", artist:"Drake", year:2015},
    {title:"Rockstar", artist:"Post Malone", year:2017},
    {title:"Circles", artist:"Post Malone", year:2019},
    {title:"Better Now", artist:"Post Malone", year:2018},
    {title:"Psycho", artist:"Post Malone", year:2018},
    {title:"Congratulations", artist:"Post Malone", year:2018},
    {title:"White Iverson", artist:"Post Malone", year:2015},
    {title:"Wow.", artist:"Post Malone", year:2019},
    {title:"Sunflower", artist:"Post Malone", year:2018},
    {title:"Lucid Dreams", artist:"Juice WRLD", year:2018},
    {title:"All Girls Are the Same", artist:"Juice WRLD", year:2018},
    {title:"Righteous", artist:"Juice WRLD", year:2020},
    {title:"SAD!", artist:"XXXTentacion", year:2018},
    {title:"Moonlight", artist:"XXXTentacion", year:2018},
    {title:"changes", artist:"XXXTentacion", year:2017},
    {title:"Jocelyn Flores", artist:"XXXTentacion", year:2017},
    {title:"Dior", artist:"Pop Smoke", year:2019},
    {title:"Welcome to the Party", artist:"Pop Smoke", year:2018},
    {title:"What You Know Bout Love", artist:"Pop Smoke", year:2020},
    {title:"The Box", artist:"Roddy Ricch", year:2019},
    {title:"Drip Too Hard", artist:"Lil Baby", year:2018},
    {title:"We Paid", artist:"Lil Baby", year:2020},
    {title:"Woah", artist:"Lil Baby", year:2019},
    {title:"Mask Off", artist:"Future", year:2017},
    {title:"Low Life", artist:"Future", year:2016},
    {title:"Super Bass", artist:"Nicki Minaj", year:2011},
    {title:"Anaconda", artist:"Nicki Minaj", year:2014},
    {title:"Starships", artist:"Nicki Minaj", year:2012},
    {title:"XO Tour Llif3", artist:"Lil Uzi Vert", year:2017},
    {title:"Just Wanna Rock", artist:"Lil Uzi Vert", year:2022},
    {title:"This Is America", artist:"Childish Gambino", year:2018},
    {title:"Redbone", artist:"Childish Gambino", year:2016},
    {title:"Rapstar", artist:"Polo G", year:2021},
    {title:"Industry Baby", artist:"Lil Nas X", year:2021},
    {title:"Montero", artist:"Lil Nas X", year:2021},
    {title:"Old Town Road", artist:"Lil Nas X", year:2019},
    {title:"Creepin", artist:"Metro Boomin", year:2022},
    {title:"Sprinter", artist:"Dave", year:2023},
    {title:"Lemon", artist:"N.E.R.D", year:2017},
    {title:"Shutdown", artist:"Skepta", year:2015},
    {title:"Vossi Bop", artist:"Stormzy", year:2019},
    {title:"Doja", artist:"Central Cee", year:2021},
    {title:"Day in the Life", artist:"Central Cee", year:2022},
    {title:"Funky Friday", artist:"Dave", year:2018},
    {title:"EARFQUAKE", artist:"Tyler the Creator", year:2019},
    {title:"See You Again", artist:"Tyler the Creator", year:2017},
    {title:"Pursuit of Happiness", artist:"Kid Cudi", year:2009},
    {title:"Mr. Rager", artist:"Kid Cudi", year:2010},
    {title:"F**kin Problems", artist:"A$AP Rocky", year:2012},
    {title:"Self Care", artist:"Mac Miller", year:2018},
    {title:"Come Back to Earth", artist:"Mac Miller", year:2018},
    {title:"Wyclef Jean", artist:"Young Thug", year:2017},
    {title:"No Lie", artist:"2 Chainz", year:2012},
    {title:"Drip or Drown", artist:"Gunna", year:2018},
    {title:"Pushin P", artist:"Gunna", year:2022},
    {title:"I Don't F**k with You", artist:"Big Sean", year:2014},
    {title:"Blessings", artist:"Chance the Rapper", year:2016},
    {title:"No Problem", artist:"Chance the Rapper", year:2016},
    {title:"Gangsta's Paradise", artist:"Coolio", year:1995},
    {title:"99 Problems", artist:"Jay-Z", year:2004},
    {title:"Empire State of Mind", artist:"Jay-Z", year:2009},
  ]},

  rnb: {label:"R&B / Soul", songs:[
    {title:"No One", artist:"Alicia Keys", year:2007},
    {title:"Fallin'", artist:"Alicia Keys", year:2001},
    {title:"Girl on Fire", artist:"Alicia Keys", year:2012},
    {title:"If I Ain't Got You", artist:"Alicia Keys", year:2003},
    {title:"All of Me", artist:"John Legend", year:2013},
    {title:"Ordinary People", artist:"John Legend", year:2004},
    {title:"So Sick", artist:"Ne-Yo", year:2006},
    {title:"Because of You", artist:"Ne-Yo", year:2007},
    {title:"Miss Independent", artist:"Ne-Yo", year:2008},
    {title:"With You", artist:"Chris Brown", year:2007},
    {title:"Forever", artist:"Chris Brown", year:2008},
    {title:"Fine China", artist:"Chris Brown", year:2013},
    {title:"Look at Me Now", artist:"Chris Brown", year:2011},
    {title:"Heartbreak Anniversary", artist:"Giveon", year:2020},
    {title:"Formation", artist:"Beyonce", year:2016},
    {title:"Love on Top", artist:"Beyonce", year:2011},
    {title:"Crazy In Love", artist:"Beyonce", year:2003},
    {title:"Halo", artist:"Beyonce", year:2008},
    {title:"Single Ladies", artist:"Beyonce", year:2008},
    {title:"Irreplaceable", artist:"Beyonce", year:2006},
    {title:"Drunk in Love", artist:"Beyonce", year:2013},
    {title:"Say My Name", artist:"Destiny's Child", year:1999},
    {title:"Survivor", artist:"Destiny's Child", year:2001},
    {title:"Bootylicious", artist:"Destiny's Child", year:2001},
    {title:"Bills, Bills, Bills", artist:"Destiny's Child", year:1999},
    {title:"Good Days", artist:"SZA", year:2020},
    {title:"Love Galore", artist:"SZA", year:2017},
    {title:"Drew Barrymore", artist:"SZA", year:2017},
    {title:"Snooze", artist:"SZA", year:2022},
    {title:"I Hate U", artist:"SZA", year:2021},
    {title:"Shirt", artist:"SZA", year:2022},
    {title:"Thinkin Bout You", artist:"Frank Ocean", year:2012},
    {title:"Super Rich Kids", artist:"Frank Ocean", year:2012},
    {title:"Swim Good", artist:"Frank Ocean", year:2011},
    {title:"Nights", artist:"Frank Ocean", year:2016},
    {title:"Lost", artist:"Frank Ocean", year:2012},
    {title:"Yeah!", artist:"Usher", year:2004},
    {title:"My Boo", artist:"Usher", year:2004},
    {title:"Burn", artist:"Usher", year:2004},
    {title:"U Got It Bad", artist:"Usher", year:2001},
    {title:"Confessions Part II", artist:"Usher", year:2004},
    {title:"Waterfalls", artist:"TLC", year:1994},
    {title:"No Scrubs", artist:"TLC", year:1999},
    {title:"Creep", artist:"TLC", year:1992},
    {title:"I Will Always Love You", artist:"Whitney Houston", year:1992},
    {title:"I Wanna Dance with Somebody", artist:"Whitney Houston", year:1987},
    {title:"Greatest Love of All", artist:"Whitney Houston", year:1986},
    {title:"How Will I Know", artist:"Whitney Houston", year:1985},
    {title:"All I Want for Christmas Is You", artist:"Mariah Carey", year:1994},
    {title:"We Belong Together", artist:"Mariah Carey", year:2005},
    {title:"Hero", artist:"Mariah Carey", year:1993},
    {title:"Fantasy", artist:"Mariah Carey", year:1995},
    {title:"Superstition", artist:"Stevie Wonder", year:1972},
    {title:"Sir Duke", artist:"Stevie Wonder", year:1977},
    {title:"Isn't She Lovely", artist:"Stevie Wonder", year:1976},
    {title:"I Just Called to Say I Love You", artist:"Stevie Wonder", year:1984},
    {title:"Respect", artist:"Aretha Franklin", year:1967},
    {title:"Think", artist:"Aretha Franklin", year:1968},
    {title:"I Say a Little Prayer", artist:"Aretha Franklin", year:1968},
    {title:"(You Make Me Feel Like) A Natural Woman", artist:"Aretha Franklin", year:1967},
    {title:"September", artist:"Earth, Wind & Fire", year:1978},
    {title:"Boogie Wonderland", artist:"Earth, Wind & Fire", year:1979},
    {title:"Hot Stuff", artist:"Donna Summer", year:1979},
    {title:"I Feel Love", artist:"Donna Summer", year:1977},
    {title:"Killing Me Softly", artist:"Fugees", year:1996},
    {title:"Leave The Door Open", artist:"Silk Sonic", year:2021},
    {title:"Boo'd Up", artist:"Ella Mai", year:2018},
    {title:"Trip", artist:"Ella Mai", year:2018},
    {title:"Exchange", artist:"Bryson Tiller", year:2015},
    {title:"Don't", artist:"Bryson Tiller", year:2015},
    {title:"Girls Need Love", artist:"Summer Walker", year:2018},
    {title:"No Love", artist:"Summer Walker", year:2019},
    {title:"Motivation", artist:"Normani", year:2019},
    {title:"Wild Side", artist:"Normani", year:2021},
    {title:"Best Part", artist:"Daniel Caesar", year:2017},
    {title:"Get You", artist:"Daniel Caesar", year:2017},
    {title:"Focus", artist:"H.E.R.", year:2017},
    {title:"2 On", artist:"Tinashe", year:2014},
    {title:"Nights Like This", artist:"Kehlani", year:2019},
    {title:"Honey", artist:"Kehlani", year:2017},
    {title:"On My Mama", artist:"Victoria Monet", year:2023},
    {title:"Pretty Wings", artist:"Maxwell", year:2009},
    {title:"Be Without You", artist:"Mary J. Blige", year:2005},
    {title:"Real Love", artist:"Mary J. Blige", year:1992},
    {title:"Again", artist:"Janet Jackson", year:1993},
    {title:"That's the Way Love Goes", artist:"Janet Jackson", year:1993},
    {title:"Untitled (How Does It Feel)", artist:"D'Angelo", year:2000},
    {title:"On & On", artist:"Erykah Badu", year:1997},
    {title:"Bag Lady", artist:"Erykah Badu", year:2000},
    {title:"Ex-Factor", artist:"Lauryn Hill", year:1998},
    {title:"Doo Wop (That Thing)", artist:"Lauryn Hill", year:1998},
    {title:"Run This Town", artist:"Jay-Z", year:2009},
    {title:"High Fashion", artist:"Roddy Ricch", year:2020},
    {title:"Come Closer", artist:"Wizkid", year:2017},
    {title:"Die For You", artist:"The Weeknd", year:2016},
    {title:"Call Out My Name", artist:"The Weeknd", year:2018},
    {title:"Earned It", artist:"The Weeknd", year:2015},
    {title:"Often", artist:"The Weeknd", year:2014},
    {title:"Latch", artist:"Disclosure", year:2012},
    {title:"Bonnie & Clyde", artist:"Beyonce", year:2002},
    {title:"Telephone", artist:"Lady Gaga", year:2009},
    {title:"Rain on Me", artist:"Lady Gaga", year:2020},
    {title:"Umbrella", artist:"Rihanna", year:2007},
    {title:"Diamonds", artist:"Rihanna", year:2012},
    {title:"We Found Love", artist:"Rihanna", year:2011},
    {title:"Only Girl", artist:"Rihanna", year:2010},
    {title:"Disturbia", artist:"Rihanna", year:2008},
    {title:"Work", artist:"Rihanna", year:2016},
  ]},

  rock: {label:"Rock", songs:[
    {title:"In The End", artist:"Linkin Park", year:2000},
    {title:"Numb", artist:"Linkin Park", year:2003},
    {title:"Crawling", artist:"Linkin Park", year:2000},
    {title:"What I've Done", artist:"Linkin Park", year:2007},
    {title:"Somewhere I Belong", artist:"Linkin Park", year:2003},
    {title:"Faint", artist:"Linkin Park", year:2003},
    {title:"Breaking the Habit", artist:"Linkin Park", year:2004},
    {title:"New Divide", artist:"Linkin Park", year:2009},
    {title:"Boulevard of Broken Dreams", artist:"Green Day", year:2004},
    {title:"American Idiot", artist:"Green Day", year:2004},
    {title:"Wake Me Up When September Ends", artist:"Green Day", year:2004},
    {title:"Basket Case", artist:"Green Day", year:1994},
    {title:"Good Riddance (Time of Your Life)", artist:"Green Day", year:1997},
    {title:"Everlong", artist:"Foo Fighters", year:1997},
    {title:"Best of You", artist:"Foo Fighters", year:2005},
    {title:"The Pretender", artist:"Foo Fighters", year:2007},
    {title:"Learn to Fly", artist:"Foo Fighters", year:1999},
    {title:"Walk", artist:"Foo Fighters", year:2011},
    {title:"All My Life", artist:"Foo Fighters", year:2002},
    {title:"Misery Business", artist:"Paramore", year:2007},
    {title:"The Only Exception", artist:"Paramore", year:2009},
    {title:"Still Into You", artist:"Paramore", year:2012},
    {title:"Ain't It Fun", artist:"Paramore", year:2013},
    {title:"Decode", artist:"Paramore", year:2008},
    {title:"Sugar, We're Goin Down", artist:"Fall Out Boy", year:2005},
    {title:"Dance Dance", artist:"Fall Out Boy", year:2005},
    {title:"Thnks fr th Mmrs", artist:"Fall Out Boy", year:2007},
    {title:"My Songs Know What You Did in the Dark", artist:"Fall Out Boy", year:2013},
    {title:"Centuries", artist:"Fall Out Boy", year:2014},
    {title:"Welcome to the Black Parade", artist:"My Chemical Romance", year:2006},
    {title:"I'm Not Okay (I Promise)", artist:"My Chemical Romance", year:2004},
    {title:"Famous Last Words", artist:"My Chemical Romance", year:2006},
    {title:"Helena", artist:"My Chemical Romance", year:2004},
    {title:"Teenagers", artist:"My Chemical Romance", year:2006},
    {title:"Do I Wanna Know?", artist:"Arctic Monkeys", year:2013},
    {title:"R U Mine?", artist:"Arctic Monkeys", year:2013},
    {title:"Fluorescent Adolescent", artist:"Arctic Monkeys", year:2011},
    {title:"505", artist:"Arctic Monkeys", year:2007},
    {title:"Why'd You Only Call Me When You're High?", artist:"Arctic Monkeys", year:2013},
    {title:"I Bet You Look Good on the Dancefloor", artist:"Arctic Monkeys", year:2005},
    {title:"Mr. Brightside", artist:"The Killers", year:2003},
    {title:"Somebody Told Me", artist:"The Killers", year:2004},
    {title:"Human", artist:"The Killers", year:2008},
    {title:"All These Things That I've Done", artist:"The Killers", year:2004},
    {title:"Yellow", artist:"Coldplay", year:2000},
    {title:"The Scientist", artist:"Coldplay", year:2002},
    {title:"Fix You", artist:"Coldplay", year:2005},
    {title:"Viva la Vida", artist:"Coldplay", year:2008},
    {title:"Speed of Sound", artist:"Coldplay", year:2005},
    {title:"Clocks", artist:"Coldplay", year:2002},
    {title:"A Sky Full of Stars", artist:"Coldplay", year:2014},
    {title:"Madness", artist:"Muse", year:2012},
    {title:"Uprising", artist:"Muse", year:2009},
    {title:"Supermassive Black Hole", artist:"Muse", year:2006},
    {title:"Starlight", artist:"Muse", year:2006},
    {title:"Time Is Running Out", artist:"Muse", year:2003},
    {title:"Believer", artist:"Imagine Dragons", year:2017},
    {title:"Thunder", artist:"Imagine Dragons", year:2017},
    {title:"Radioactive", artist:"Imagine Dragons", year:2012},
    {title:"Natural", artist:"Imagine Dragons", year:2018},
    {title:"Demons", artist:"Imagine Dragons", year:2012},
    {title:"Smells Like Teen Spirit", artist:"Nirvana", year:1991},
    {title:"Come As You Are", artist:"Nirvana", year:1991},
    {title:"Heart-Shaped Box", artist:"Nirvana", year:1993},
    {title:"Under The Bridge", artist:"Red Hot Chili Peppers", year:1991},
    {title:"Californication", artist:"Red Hot Chili Peppers", year:1999},
    {title:"Scar Tissue", artist:"Red Hot Chili Peppers", year:1999},
    {title:"Wonderwall", artist:"Oasis", year:1995},
    {title:"Don't Look Back In Anger", artist:"Oasis", year:1996},
    {title:"Champagne Supernova", artist:"Oasis", year:1995},
    {title:"Sweet Child O' Mine", artist:"Guns N' Roses", year:1987},
    {title:"Welcome to the Jungle", artist:"Guns N' Roses", year:1987},
    {title:"Paradise City", artist:"Guns N' Roses", year:1987},
    {title:"November Rain", artist:"Guns N' Roses", year:1991},
    {title:"Back in Black", artist:"AC/DC", year:1980},
    {title:"Highway to Hell", artist:"AC/DC", year:1979},
    {title:"Thunderstruck", artist:"AC/DC", year:1990},
    {title:"You Shook Me All Night Long", artist:"AC/DC", year:1980},
    {title:"Enter Sandman", artist:"Metallica", year:1991},
    {title:"Nothing Else Matters", artist:"Metallica", year:1991},
    {title:"The Unforgiven", artist:"Metallica", year:1991},
    {title:"Master of Puppets", artist:"Metallica", year:1986},
    {title:"Seven Nation Army", artist:"The White Stripes", year:2003},
    {title:"Icky Thump", artist:"The White Stripes", year:2007},
    {title:"Last Nite", artist:"The Strokes", year:2001},
    {title:"Reptilia", artist:"The Strokes", year:2003},
    {title:"Karma Police", artist:"Radiohead", year:1997},
    {title:"Creep", artist:"Radiohead", year:1992},
    {title:"No Surprises", artist:"Radiohead", year:1997},
    {title:"Song 2", artist:"Blur", year:1997},
    {title:"Even Flow", artist:"Pearl Jam", year:1991},
    {title:"Jeremy", artist:"Pearl Jam", year:1991},
    {title:"Black Hole Sun", artist:"Soundgarden", year:1994},
    {title:"Killing in the Name", artist:"Rage Against the Machine", year:1991},
    {title:"Chop Suey!", artist:"System of a Down", year:2001},
    {title:"All the Small Things", artist:"Blink-182", year:2000},
    {title:"I Miss You", artist:"Blink-182", year:2003},
    {title:"Sex on Fire", artist:"Kings of Leon", year:2008},
    {title:"Use Somebody", artist:"Kings of Leon", year:2008},
    {title:"Ain't No Rest for the Wicked", artist:"Cage the Elephant", year:2008},
    {title:"Stairway to Heaven", artist:"Led Zeppelin", year:1971},
    {title:"Whole Lotta Love", artist:"Led Zeppelin", year:1969},
    {title:"Kashmir", artist:"Led Zeppelin", year:1975},
    {title:"Immigrant Song", artist:"Led Zeppelin", year:1970},
    {title:"Hotel California", artist:"Eagles", year:1977},
    {title:"Dream On", artist:"Aerosmith", year:1973},
    {title:"I Don't Want to Miss a Thing", artist:"Aerosmith", year:1998},
    {title:"Take Me to Church", artist:"Hozier", year:2013},
    {title:"Work Song", artist:"Hozier", year:2014},
    {title:"Losing My Religion", artist:"R.E.M.", year:1991},
    {title:"Semi-Charmed Life", artist:"Third Eye Blind", year:1997},
    {title:"Bullet with Butterfly Wings", artist:"Smashing Pumpkins", year:1995},
    {title:"1979", artist:"Smashing Pumpkins", year:1995},
    {title:"Buddy Holly", artist:"Weezer", year:1994},
    {title:"Island in the Sun", artist:"Weezer", year:2001},
    {title:"Fat Lip", artist:"Sum 41", year:2001},
  ]},

  throwbacks: {label:"Throwbacks", songs:[
    {title:"Take On Me", artist:"a-ha", year:1985},
    {title:"Don't You Want Me", artist:"Human League", year:1981},
    {title:"Total Eclipse of the Heart", artist:"Bonnie Tyler", year:1983},
    {title:"Africa", artist:"Toto", year:1982},
    {title:"Don't Stop Believin'", artist:"Journey", year:1981},
    {title:"Eye of the Tiger", artist:"Survivor", year:1982},
    {title:"Girls Just Wanna Have Fun", artist:"Cyndi Lauper", year:1983},
    {title:"Time After Time", artist:"Cyndi Lauper", year:1983},
    {title:"Like a Prayer", artist:"Madonna", year:1989},
    {title:"Material Girl", artist:"Madonna", year:1984},
    {title:"Papa Don't Preach", artist:"Madonna", year:1986},
    {title:"Like a Virgin", artist:"Madonna", year:1984},
    {title:"Vogue", artist:"Madonna", year:1990},
    {title:"Wake Me Up Before You Go-Go", artist:"Wham!", year:1984},
    {title:"Careless Whisper", artist:"George Michael", year:1984},
    {title:"Faith", artist:"George Michael", year:1987},
    {title:"Billie Jean", artist:"Michael Jackson", year:1982},
    {title:"Thriller", artist:"Michael Jackson", year:1982},
    {title:"Beat It", artist:"Michael Jackson", year:1982},
    {title:"Man In The Mirror", artist:"Michael Jackson", year:1987},
    {title:"Smooth Criminal", artist:"Michael Jackson", year:1987},
    {title:"Don't Stop 'Til You Get Enough", artist:"Michael Jackson", year:1979},
    {title:"Bohemian Rhapsody", artist:"Queen", year:1975},
    {title:"Don't Stop Me Now", artist:"Queen", year:1978},
    {title:"We Will Rock You", artist:"Queen", year:1977},
    {title:"Radio Ga Ga", artist:"Queen", year:1984},
    {title:"Under Pressure", artist:"Queen", year:1981},
    {title:"Purple Rain", artist:"Prince", year:1984},
    {title:"Kiss", artist:"Prince", year:1986},
    {title:"When Doves Cry", artist:"Prince", year:1984},
    {title:"Let's Go Crazy", artist:"Prince", year:1984},
    {title:"Heroes", artist:"David Bowie", year:1977},
    {title:"Let's Dance", artist:"David Bowie", year:1983},
    {title:"Space Oddity", artist:"David Bowie", year:1969},
    {title:"Life on Mars?", artist:"David Bowie", year:1971},
    {title:"Rocket Man", artist:"Elton John", year:1972},
    {title:"Tiny Dancer", artist:"Elton John", year:1971},
    {title:"Crocodile Rock", artist:"Elton John", year:1972},
    {title:"Your Song", artist:"Elton John", year:1970},
    {title:"I'm Still Standing", artist:"Elton John", year:1983},
    {title:"Goodbye Yellow Brick Road", artist:"Elton John", year:1973},
    {title:"In the Air Tonight", artist:"Phil Collins", year:1981},
    {title:"Against All Odds", artist:"Phil Collins", year:1984},
    {title:"Another Day in Paradise", artist:"Phil Collins", year:1989},
    {title:"You Can't Hurry Love", artist:"Phil Collins", year:1983},
    {title:"Dancing Queen", artist:"ABBA", year:1976},
    {title:"Waterloo", artist:"ABBA", year:1974},
    {title:"Mamma Mia", artist:"ABBA", year:1975},
    {title:"Fernando", artist:"ABBA", year:1976},
    {title:"The Winner Takes It All", artist:"ABBA", year:1980},
    {title:"Gimme! Gimme! Gimme!", artist:"ABBA", year:1979},
    {title:"Born to Run", artist:"Bruce Springsteen", year:1975},
    {title:"Dancing in the Dark", artist:"Bruce Springsteen", year:1984},
    {title:"Born in the USA", artist:"Bruce Springsteen", year:1984},
    {title:"My Way", artist:"Frank Sinatra", year:1969},
    {title:"Fly Me to the Moon", artist:"Frank Sinatra", year:1964},
    {title:"New York, New York", artist:"Frank Sinatra", year:1980},
    {title:"Jailhouse Rock", artist:"Elvis Presley", year:1957},
    {title:"Suspicious Minds", artist:"Elvis Presley", year:1969},
    {title:"Can't Help Falling in Love", artist:"Elvis Presley", year:1961},
    {title:"Hound Dog", artist:"Elvis Presley", year:1956},
    {title:"(I Can't Get No) Satisfaction", artist:"The Rolling Stones", year:1965},
    {title:"Paint It Black", artist:"The Rolling Stones", year:1966},
    {title:"Sympathy for the Devil", artist:"The Rolling Stones", year:1968},
    {title:"Hey Jude", artist:"The Beatles", year:1968},
    {title:"Let It Be", artist:"The Beatles", year:1970},
    {title:"Come Together", artist:"The Beatles", year:1969},
    {title:"Yesterday", artist:"The Beatles", year:1965},
    {title:"Here Comes the Sun", artist:"The Beatles", year:1969},
    {title:"Twist and Shout", artist:"The Beatles", year:1963},
    {title:"...Baby One More Time", artist:"Britney Spears", year:1998},
    {title:"Toxic", artist:"Britney Spears", year:2003},
    {title:"Oops!... I Did It Again", artist:"Britney Spears", year:2000},
    {title:"Wannabe", artist:"Spice Girls", year:1996},
    {title:"Say You'll Be There", artist:"Spice Girls", year:1996},
    {title:"I Want It That Way", artist:"Backstreet Boys", year:1999},
    {title:"Everybody", artist:"Backstreet Boys", year:1997},
    {title:"Quit Playing Games", artist:"Backstreet Boys", year:1996},
    {title:"Bye Bye Bye", artist:"NSYNC", year:2000},
    {title:"Tearin' Up My Heart", artist:"NSYNC", year:1997},
    {title:"MMMBop", artist:"Hanson", year:1997},
    {title:"Complicated", artist:"Avril Lavigne", year:2002},
    {title:"Girlfriend", artist:"Avril Lavigne", year:2007},
    {title:"Sk8er Boi", artist:"Avril Lavigne", year:2002},
    {title:"Since U Been Gone", artist:"Kelly Clarkson", year:2004},
    {title:"Beautiful", artist:"Christina Aguilera", year:2002},
    {title:"Genie in a Bottle", artist:"Christina Aguilera", year:1999},
    {title:"What a Girl Wants", artist:"Christina Aguilera", year:1999},
    {title:"California Gurls", artist:"Katy Perry", year:2010},
    {title:"Roar", artist:"Katy Perry", year:2013},
    {title:"Firework", artist:"Katy Perry", year:2010},
    {title:"Dark Horse", artist:"Katy Perry", year:2013},
    {title:"Teenage Dream", artist:"Katy Perry", year:2010},
    {title:"Party In The U.S.A.", artist:"Miley Cyrus", year:2009},
    {title:"Bad Romance", artist:"Lady Gaga", year:2009},
    {title:"Just Dance", artist:"Lady Gaga", year:2008},
    {title:"Poker Face", artist:"Lady Gaga", year:2008},
    {title:"I Gotta Feeling", artist:"Black Eyed Peas", year:2009},
    {title:"Boom Boom Pow", artist:"Black Eyed Peas", year:2009},
    {title:"Where Is the Love", artist:"Black Eyed Peas", year:2003},
    {title:"Hot in Herre", artist:"Nelly", year:2002},
    {title:"Dilemma", artist:"Nelly", year:2002},
    {title:"Right Round", artist:"Flo Rida", year:2009},
    {title:"Tik Tok", artist:"Kesha", year:2009},
    {title:"Running Up That Hill", artist:"Kate Bush", year:1985},
    {title:"Rhythm Is a Dancer", artist:"Snap!", year:1992},
    {title:"Freed from Desire", artist:"Gala", year:1997},
    {title:"Livin' on a Prayer", artist:"Bon Jovi", year:1986},
    {title:"You Give Love a Bad Name", artist:"Bon Jovi", year:1986},
    {title:"Another Brick in the Wall", artist:"Pink Floyd", year:1979},
    {title:"Wish You Were Here", artist:"Pink Floyd", year:1975},
    {title:"Comfortably Numb", artist:"Pink Floyd", year:1979},
    {title:"One More Time", artist:"Daft Punk", year:2000},
    {title:"Get Lucky", artist:"Daft Punk", year:2013},
  ]},

  kpop: {label:"K-Pop", songs:[
    {title:"Butter", artist:"BTS", year:2021},
    {title:"Dynamite", artist:"BTS", year:2020},
    {title:"Permission to Dance", artist:"BTS", year:2021},
    {title:"Boy With Luv", artist:"BTS", year:2019},
    {title:"DNA", artist:"BTS", year:2017},
    {title:"Fake Love", artist:"BTS", year:2018},
    {title:"Spring Day", artist:"BTS", year:2017},
    {title:"Life Goes On", artist:"BTS", year:2020},
    {title:"ON", artist:"BTS", year:2020},
    {title:"Mic Drop", artist:"BTS", year:2017},
    {title:"Blood Sweat & Tears", artist:"BTS", year:2016},
    {title:"Fire", artist:"BTS", year:2016},
    {title:"Run", artist:"BTS", year:2015},
    {title:"I Need U", artist:"BTS", year:2015},
    {title:"Idol", artist:"BTS", year:2018},
    {title:"Black Swan", artist:"BTS", year:2020},
    {title:"Yet To Come", artist:"BTS", year:2022},
    {title:"How You Like That", artist:"BLACKPINK", year:2020},
    {title:"Lovesick Girls", artist:"BLACKPINK", year:2020},
    {title:"Pink Venom", artist:"BLACKPINK", year:2022},
    {title:"Ddu-Du Ddu-Du", artist:"BLACKPINK", year:2018},
    {title:"Ice Cream", artist:"BLACKPINK", year:2020},
    {title:"Boombayah", artist:"BLACKPINK", year:2016},
    {title:"Whistle", artist:"BLACKPINK", year:2016},
    {title:"Playing With Fire", artist:"BLACKPINK", year:2016},
    {title:"Kill This Love", artist:"BLACKPINK", year:2019},
    {title:"As If It's Your Last", artist:"BLACKPINK", year:2017},
    {title:"Miroh", artist:"Stray Kids", year:2019},
    {title:"God's Menu", artist:"Stray Kids", year:2020},
    {title:"Back Door", artist:"Stray Kids", year:2020},
    {title:"Maniac", artist:"Stray Kids", year:2022},
    {title:"CASE 143", artist:"Stray Kids", year:2022},
    {title:"Thunderous", artist:"Stray Kids", year:2021},
    {title:"District 9", artist:"Stray Kids", year:2018},
    {title:"Side Effects", artist:"Stray Kids", year:2019},
    {title:"MIROH", artist:"Stray Kids", year:2019},
    {title:"Black Mamba", artist:"aespa", year:2020},
    {title:"Next Level", artist:"aespa", year:2021},
    {title:"Savage", artist:"aespa", year:2021},
    {title:"Girls", artist:"aespa", year:2022},
    {title:"Drama", artist:"aespa", year:2023},
    {title:"Spicy", artist:"aespa", year:2023},
    {title:"Cheer Up", artist:"TWICE", year:2016},
    {title:"TT", artist:"TWICE", year:2016},
    {title:"What is Love?", artist:"TWICE", year:2018},
    {title:"YES or YES", artist:"TWICE", year:2018},
    {title:"I Can't Stop Me", artist:"TWICE", year:2020},
    {title:"Talk that Talk", artist:"TWICE", year:2022},
    {title:"Heart Shaker", artist:"TWICE", year:2017},
    {title:"More & More", artist:"TWICE", year:2020},
    {title:"Growl", artist:"EXO", year:2013},
    {title:"Monster", artist:"EXO", year:2016},
    {title:"Power", artist:"EXO", year:2017},
    {title:"Ko Ko Bop", artist:"EXO", year:2017},
    {title:"Overdose", artist:"EXO", year:2014},
    {title:"Regular", artist:"NCT 127", year:2018},
    {title:"Simon Says", artist:"NCT 127", year:2018},
    {title:"Kick It", artist:"NCT 127", year:2020},
    {title:"Sticker", artist:"NCT 127", year:2021},
    {title:"2 Baddies", artist:"NCT 127", year:2022},
    {title:"ELEVEN", artist:"IVE", year:2021},
    {title:"Love Dive", artist:"IVE", year:2022},
    {title:"After LIKE", artist:"IVE", year:2022},
    {title:"I AM", artist:"IVE", year:2023},
    {title:"Baddie", artist:"IVE", year:2023},
    {title:"Hype Boy", artist:"NewJeans", year:2022},
    {title:"Attention", artist:"NewJeans", year:2022},
    {title:"Ditto", artist:"NewJeans", year:2022},
    {title:"OMG", artist:"NewJeans", year:2023},
    {title:"Super Shy", artist:"NewJeans", year:2023},
    {title:"ETA", artist:"NewJeans", year:2023},
    {title:"Fantastic Baby", artist:"BIGBANG", year:2012},
    {title:"Bang Bang Bang", artist:"BIGBANG", year:2015},
    {title:"FXXK IT", artist:"BIGBANG", year:2016},
    {title:"Lies", artist:"BIGBANG", year:2007},
    {title:"Ring Ding Dong", artist:"SHINee", year:2009},
    {title:"Lucifer", artist:"SHINee", year:2010},
    {title:"View", artist:"SHINee", year:2015},
    {title:"I Am the Best", artist:"2NE1", year:2011},
    {title:"Fire", artist:"2NE1", year:2009},
    {title:"Sorry Sorry", artist:"Super Junior", year:2009},
    {title:"Good Day", artist:"IU", year:2010},
    {title:"Celebrity", artist:"IU", year:2021},
    {title:"Through the Night", artist:"IU", year:2017},
    {title:"BBIBBI", artist:"IU", year:2018},
    {title:"Any Song", artist:"Zico", year:2020},
    {title:"Don't Wanna Cry", artist:"Seventeen", year:2017},
    {title:"Left & Right", artist:"Seventeen", year:2020},
    {title:"Rock With You", artist:"Seventeen", year:2021},
    {title:"0X1=LOVESONG", artist:"TXT", year:2021},
    {title:"Can't You See Me?", artist:"TXT", year:2020},
    {title:"Sugar Rush Ride", artist:"TXT", year:2023},
    {title:"Hero", artist:"MONSTA X", year:2015},
    {title:"Shoot Out", artist:"MONSTA X", year:2018},
    {title:"Hard Carry", artist:"GOT7", year:2016},
    {title:"Lullaby", artist:"GOT7", year:2018},
    {title:"Love$ick", artist:"Mura Masa", year:2016},
    {title:"Really Really", artist:"WINNER", year:2017},
    {title:"Beautiful", artist:"Crush", year:2016},
    {title:"Crayon", artist:"G-Dragon", year:2012},
    {title:"One of a Kind", artist:"G-Dragon", year:2012},
    {title:"Taeyang - EYES, NOSE, LIPS", artist:"Taeyang", year:2014},
    {title:"Wedding Dress", artist:"Taeyang", year:2009},
  ]},

  electronic: {label:"Electronic / Dance", songs:[
    {title:"Levels", artist:"Avicii", year:2011},
    {title:"Wake Me Up", artist:"Avicii", year:2013},
    {title:"Hey Brother", artist:"Avicii", year:2013},
    {title:"Addicted to You", artist:"Avicii", year:2013},
    {title:"SOS", artist:"Avicii", year:2019},
    {title:"Silhouettes", artist:"Avicii", year:2012},
    {title:"I Could Be the One", artist:"Avicii", year:2012},
    {title:"Animals", artist:"Martin Garrix", year:2013},
    {title:"In The Name Of Love", artist:"Martin Garrix", year:2016},
    {title:"Titanium", artist:"David Guetta", year:2011},
    {title:"Turn Me On", artist:"David Guetta", year:2011},
    {title:"Play Hard", artist:"David Guetta", year:2013},
    {title:"Hey Mama", artist:"David Guetta", year:2015},
    {title:"Where Dem Girls At", artist:"David Guetta", year:2011},
    {title:"Clarity", artist:"Zedd", year:2012},
    {title:"Beautiful Now", artist:"Zedd", year:2015},
    {title:"The Middle", artist:"Zedd", year:2018},
    {title:"Magnets", artist:"Disclosure", year:2015},
    {title:"Holding On", artist:"Disclosure", year:2015},
    {title:"White Noise", artist:"Disclosure", year:2012},
    {title:"Rather Be", artist:"Clean Bandit", year:2014},
    {title:"Rockabye", artist:"Clean Bandit", year:2016},
    {title:"Symphony", artist:"Clean Bandit", year:2017},
    {title:"Solo", artist:"Clean Bandit", year:2018},
    {title:"Closer", artist:"The Chainsmokers", year:2016},
    {title:"Don't Let Me Down", artist:"The Chainsmokers", year:2016},
    {title:"Paris", artist:"The Chainsmokers", year:2017},
    {title:"Roses", artist:"The Chainsmokers", year:2015},
    {title:"Happier", artist:"Marshmello", year:2018},
    {title:"Friends", artist:"Marshmello", year:2018},
    {title:"Silence", artist:"Marshmello", year:2017},
    {title:"Alone", artist:"Marshmello", year:2016},
    {title:"Summer", artist:"Calvin Harris", year:2014},
    {title:"Feel So Close", artist:"Calvin Harris", year:2011},
    {title:"Outside", artist:"Calvin Harris", year:2014},
    {title:"How Deep Is Your Love", artist:"Calvin Harris", year:2015},
    {title:"This Is What You Came For", artist:"Calvin Harris", year:2016},
    {title:"Promises", artist:"Calvin Harris", year:2018},
    {title:"Faking It", artist:"Calvin Harris", year:2017},
    {title:"Taki Taki", artist:"DJ Snake", year:2018},
    {title:"Turn Down for What", artist:"DJ Snake", year:2013},
    {title:"Let Me Love You", artist:"DJ Snake", year:2016},
    {title:"Middle", artist:"DJ Snake", year:2016},
    {title:"Elastic Heart", artist:"Sia", year:2015},
    {title:"The Greatest", artist:"Sia", year:2016},
    {title:"Don't You Worry Child", artist:"Swedish House Mafia", year:2012},
    {title:"One", artist:"Swedish House Mafia", year:2010},
    {title:"Moth To A Flame", artist:"Swedish House Mafia", year:2021},
    {title:"The Business", artist:"Tiësto", year:2020},
    {title:"Red Lights", artist:"Tiësto", year:2014},
    {title:"Boom", artist:"Tiësto", year:2020},
    {title:"Firestone", artist:"Kygo", year:2014},
    {title:"Stole the Show", artist:"Kygo", year:2015},
    {title:"Here for You", artist:"Kygo", year:2015},
    {title:"Happy Now", artist:"Kygo", year:2018},
    {title:"Never Be Like You", artist:"Flume", year:2016},
    {title:"Say It", artist:"Flume", year:2016},
    {title:"Scary Monsters and Nice Sprites", artist:"Skrillex", year:2010},
    {title:"First of the Year", artist:"Skrillex", year:2012},
    {title:"Ghosts n Stuff", artist:"Deadmau5", year:2009},
    {title:"Strobe", artist:"Deadmau5", year:2009},
    {title:"Runaway (U & I)", artist:"Galantis", year:2014},
    {title:"No Money", artist:"Galantis", year:2016},
    {title:"Heroes (we could be)", artist:"Alesso", year:2014},
    {title:"Cool", artist:"Alesso", year:2020},
    {title:"Ain't Nobody", artist:"Felix Jaehn", year:2015},
    {title:"Nobody To Love", artist:"Sigma", year:2014},
    {title:"Ocean Drive", artist:"Duke Dumont", year:2015},
    {title:"I Got U", artist:"Duke Dumont", year:2014},
    {title:"Head & Heart", artist:"Joel Corry", year:2020},
    {title:"Breaking Me", artist:"Topic", year:2020},
    {title:"Losing It", artist:"Fisher", year:2018},
    {title:"(It Goes Like) Nanana", artist:"Peggy Gou", year:2023},
    {title:"Lean On", artist:"Major Lazer", year:2015},
    {title:"Cold Water", artist:"Major Lazer", year:2016},
    {title:"Lights", artist:"Ellie Goulding", year:2010},
    {title:"Burn", artist:"Ellie Goulding", year:2013},
    {title:"Love Me Like You Do", artist:"Ellie Goulding", year:2015},
    {title:"On My Mind", artist:"Ellie Goulding", year:2015},
    {title:"Instant Crush", artist:"Daft Punk", year:2013},
    {title:"Spaceman", artist:"Hardwell", year:2013},
    {title:"Ferrari", artist:"James Hype", year:2022},
    {title:"Roses (Imanbek Remix)", artist:"SAINt JHN", year:2019},
    {title:"Ready for Your Love", artist:"Gorgon City", year:2014},
    {title:"Innerbloom", artist:"Rufus du Sol", year:2016},
    {title:"Say My Name", artist:"Odesza", year:2017},
    {title:"A Moment Apart", artist:"Odesza", year:2017},
    {title:"Higher Ground", artist:"Odesza", year:2022},
    {title:"Cheerleader", artist:"Omi", year:2015},
    {title:"Like I Do", artist:"Martin Garrix", year:2018},
    {title:"Pompeii", artist:"Bastille", year:2013},
    {title:"Good Grief", artist:"Bastille", year:2016},
    {title:"Power", artist:"Ellie Goulding", year:2017},
    {title:"I Remember", artist:"Deadmau5", year:2009},
    {title:"Stay the Night", artist:"Zedd", year:2013},
    {title:"Beautiful People", artist:"Ed Sheeran", year:2019},
    {title:"Glad You Came", artist:"The Wanted", year:2011},
    {title:"Spectrum", artist:"Florence + The Machine", year:2011},
    {title:"Stay the Night", artist:"Zedd", year:2013},
    {title:"Glad You Came", artist:"The Wanted", year:2011},
    {title:"Rockabye Baby", artist:"Clean Bandit", year:2016},
    {title:"Midnight City", artist:"M83", year:2011},
    {title:"Wait", artist:"M83", year:2016},
  ]},

  afrobeats: {label:"Afrobeats / Latin", songs:[
    {title:"Calm Down", artist:"Rema", year:2022},
    {title:"Essence", artist:"Wizkid", year:2020},
    {title:"Joro", artist:"Wizkid", year:2019},
    {title:"Blessed", artist:"Wizkid", year:2017},
    {title:"Afro Nation", artist:"Wizkid", year:2021},
    {title:"Last Last", artist:"Burna Boy", year:2022},
    {title:"Ye", artist:"Burna Boy", year:2018},
    {title:"On the Low", artist:"Burna Boy", year:2019},
    {title:"Way Too Big", artist:"Burna Boy", year:2020},
    {title:"Anybody", artist:"Burna Boy", year:2018},
    {title:"City Boys", artist:"Burna Boy", year:2021},
    {title:"Kilometre", artist:"Burna Boy", year:2019},
    {title:"Fall", artist:"Davido", year:2017},
    {title:"Assurance", artist:"Davido", year:2018},
    {title:"FEM", artist:"Davido", year:2020},
    {title:"Stand Strong", artist:"Davido", year:2022},
    {title:"If", artist:"Davido", year:2017},
    {title:"Peru", artist:"Fireboy DML", year:2021},
    {title:"Jealous", artist:"Fireboy DML", year:2019},
    {title:"Champion", artist:"Fireboy DML", year:2020},
    {title:"Bad Influence", artist:"Omah Lay", year:2020},
    {title:"Damn", artist:"Omah Lay", year:2020},
    {title:"Free Mind", artist:"Tems", year:2020},
    {title:"Found", artist:"Tems", year:2020},
    {title:"Love Nwantiti", artist:"CKay", year:2019},
    {title:"Rush", artist:"Ayra Starr", year:2023},
    {title:"Away", artist:"Ayra Starr", year:2022},
    {title:"Sungba", artist:"Asake", year:2022},
    {title:"Organise", artist:"Asake", year:2022},
    {title:"Mr. Money with the Vibe", artist:"Asake", year:2022},
    {title:"Buga", artist:"Kizz Daniel", year:2022},
    {title:"Kwaku the Traveller", artist:"Black Sherif", year:2022},
    {title:"Baby", artist:"Joeboy", year:2019},
    {title:"Mr Eazi - Leg Over", artist:"Mr Eazi", year:2017},
    {title:"Pour Me Water", artist:"Mr Eazi", year:2017},
    {title:"Dakiti", artist:"Bad Bunny", year:2020},
    {title:"Titi Me Pregunto", artist:"Bad Bunny", year:2022},
    {title:"Me Porto Bonito", artist:"Bad Bunny", year:2022},
    {title:"Yonaguni", artist:"Bad Bunny", year:2021},
    {title:"MIA", artist:"Bad Bunny", year:2018},
    {title:"Moscow Mule", artist:"Bad Bunny", year:2022},
    {title:"Efecto", artist:"Bad Bunny", year:2022},
    {title:"La Corriente", artist:"Bad Bunny", year:2022},
    {title:"Hips Don't Lie", artist:"Shakira", year:2006},
    {title:"Waka Waka (This Time for Africa)", artist:"Shakira", year:2010},
    {title:"Whenever, Wherever", artist:"Shakira", year:2001},
    {title:"She Wolf", artist:"Shakira", year:2009},
    {title:"Loca", artist:"Shakira", year:2010},
    {title:"Gasolina", artist:"Daddy Yankee", year:2004},
    {title:"Con Calma", artist:"Daddy Yankee", year:2019},
    {title:"Mi Gente", artist:"J Balvin", year:2017},
    {title:"Safari", artist:"J Balvin", year:2016},
    {title:"RITMO", artist:"J Balvin", year:2019},
    {title:"Hawái", artist:"Maluma", year:2020},
    {title:"Felices los 4", artist:"Maluma", year:2017},
    {title:"ADMV", artist:"Maluma", year:2020},
    {title:"Despacito", artist:"Luis Fonsi", year:2017},
    {title:"Tusa", artist:"Karol G", year:2019},
    {title:"MAMIII", artist:"Karol G", year:2022},
    {title:"TQG", artist:"Karol G", year:2023},
    {title:"Provenza", artist:"Karol G", year:2022},
    {title:"Bichota", artist:"Karol G", year:2020},
    {title:"Con Altura", artist:"Rosalia", year:2019},
    {title:"SAOKO", artist:"Rosalia", year:2022},
    {title:"China", artist:"Anuel AA", year:2019},
    {title:"Otro Trago", artist:"Sech", year:2019},
    {title:"Vida de Rico", artist:"Camilo", year:2020},
    {title:"On the Floor", artist:"Jennifer Lopez", year:2011},
    {title:"Jenny from the Block", artist:"Jennifer Lopez", year:2002},
    {title:"Hero", artist:"Enrique Iglesias", year:2001},
    {title:"Bailando", artist:"Enrique Iglesias", year:2014},
    {title:"I Like It", artist:"Enrique Iglesias", year:2010},
    {title:"Livin' la Vida Loca", artist:"Ricky Martin", year:1999},
    {title:"She Bangs", artist:"Ricky Martin", year:2000},
    {title:"Vivir Mi Vida", artist:"Marc Anthony", year:2013},
    {title:"Danza Kuduro", artist:"Don Omar", year:2010},
    {title:"One Dance", artist:"Drake", year:2016},
    {title:"Lean On", artist:"Major Lazer", year:2015},
    {title:"Run the World (Girls)", artist:"Beyonce", year:2011},
    {title:"Ojuelegba", artist:"Wizkid", year:2014},
    {title:"Ye Mo", artist:"Kizz Daniel", year:2021},
    {title:"Nakupenda", artist:"Fireboy DML", year:2022},
    {title:"Favourite", artist:"Burna Boy", year:2019},
    {title:"Location", artist:"Khalid", year:2016},
    {title:"Lovely Day", artist:"Adekunle Gold", year:2023},
    {title:"Okay", artist:"Adekunle Gold", year:2019},
    {title:"Most Original", artist:"Stonebwoy", year:2020},
    {title:"Coming Home", artist:"Davido", year:2021},
    {title:"Peru (Remix)", artist:"Fireboy DML", year:2021},
    {title:"Do Yourself", artist:"Burna Boy", year:2023},
    {title:"Jogodo", artist:"Tekno", year:2017},
    {title:"Wetin We Gain", artist:"Victor AD", year:2018},
    {title:"Fefe", artist:"6ix9ine", year:2018},
    {title:"No Woman No Cry", artist:"Wizkid", year:2021},
    {title:"Sugarcane", artist:"Camilo", year:2021},
    {title:"Sin Pijama", artist:"Becky G", year:2018},
    {title:"Dollar", artist:"Becky G", year:2019},
    {title:"Naughty by Nature", artist:"Burna Boy", year:2023},
    {title:"Rihanna", artist:"Yemi Alade", year:2014},
    {title:"Johnny", artist:"Yemi Alade", year:2014},
    {title:"Monalisa", artist:"Lojay", year:2021},
    {title:"Buga (Lo Lo Lo)", artist:"Kizz Daniel", year:2022},
  ]},

  indie: {label:"Indie / Alt", songs:[
    {title:"Video Games", artist:"Lana Del Rey", year:2011},
    {title:"Summertime Sadness", artist:"Lana Del Rey", year:2012},
    {title:"Young and Beautiful", artist:"Lana Del Rey", year:2013},
    {title:"Born to Die", artist:"Lana Del Rey", year:2012},
    {title:"Ride", artist:"Lana Del Rey", year:2012},
    {title:"The Less I Know the Better", artist:"Tame Impala", year:2015},
    {title:"Let It Happen", artist:"Tame Impala", year:2015},
    {title:"Elephant", artist:"Tame Impala", year:2012},
    {title:"Lost in Yesterday", artist:"Tame Impala", year:2020},
    {title:"Eventually", artist:"Tame Impala", year:2015},
    {title:"Rehab", artist:"Amy Winehouse", year:2006},
    {title:"Back to Black", artist:"Amy Winehouse", year:2006},
    {title:"Valerie", artist:"Amy Winehouse", year:2007},
    {title:"Tears Dry on Their Own", artist:"Amy Winehouse", year:2007},
    {title:"Chocolate", artist:"The 1975", year:2013},
    {title:"Sex", artist:"The 1975", year:2013},
    {title:"The Sound", artist:"The 1975", year:2016},
    {title:"Somebody Else", artist:"The 1975", year:2016},
    {title:"If You're Too Shy (Let Me Know)", artist:"The 1975", year:2020},
    {title:"Love Me", artist:"The 1975", year:2016},
    {title:"Ho Hey", artist:"The Lumineers", year:2012},
    {title:"Ophelia", artist:"The Lumineers", year:2016},
    {title:"Gloria", artist:"The Lumineers", year:2019},
    {title:"Little Talks", artist:"Of Monsters and Men", year:2011},
    {title:"Mountain Sound", artist:"Of Monsters and Men", year:2012},
    {title:"Little Lion Man", artist:"Mumford & Sons", year:2009},
    {title:"The Cave", artist:"Mumford & Sons", year:2009},
    {title:"I Will Wait", artist:"Mumford & Sons", year:2012},
    {title:"Lover of the Light", artist:"Mumford & Sons", year:2012},
    {title:"Dog Days Are Over", artist:"Florence + The Machine", year:2008},
    {title:"Shake It Out", artist:"Florence + The Machine", year:2011},
    {title:"Hunger", artist:"Florence + The Machine", year:2018},
    {title:"Never Let Me Go", artist:"Florence + The Machine", year:2011},
    {title:"Cosmic Love", artist:"Florence + The Machine", year:2009},
    {title:"Skinny Love", artist:"Bon Iver", year:2007},
    {title:"Holocene", artist:"Bon Iver", year:2011},
    {title:"For Emma", artist:"Bon Iver", year:2008},
    {title:"Perth", artist:"Bon Iver", year:2011},
    {title:"Savior Complex", artist:"Phoebe Bridgers", year:2020},
    {title:"Garden Song", artist:"Phoebe Bridgers", year:2020},
    {title:"Kyoto", artist:"Phoebe Bridgers", year:2020},
    {title:"Moon Song", artist:"Phoebe Bridgers", year:2020},
    {title:"Funeral", artist:"Phoebe Bridgers", year:2017},
    {title:"Not Strong Enough", artist:"boygenius", year:2023},
    {title:"Wake Up", artist:"Arcade Fire", year:2004},
    {title:"Rebellion (Lies)", artist:"Arcade Fire", year:2004},
    {title:"Sprawl II", artist:"Arcade Fire", year:2010},
    {title:"Reflektor", artist:"Arcade Fire", year:2013},
    {title:"A-Punk", artist:"Vampire Weekend", year:2008},
    {title:"Oxford Comma", artist:"Vampire Weekend", year:2008},
    {title:"Cousins", artist:"Vampire Weekend", year:2010},
    {title:"Harmony Hall", artist:"Vampire Weekend", year:2019},
    {title:"Bloodbuzz Ohio", artist:"The National", year:2010},
    {title:"About Today", artist:"The National", year:2004},
    {title:"Sorrow", artist:"The National", year:2010},
    {title:"I Will Follow You into the Dark", artist:"Death Cab for Cutie", year:2005},
    {title:"Soul Meets Body", artist:"Death Cab for Cutie", year:2005},
    {title:"Such Great Heights", artist:"The Postal Service", year:2003},
    {title:"1234", artist:"Feist", year:2007},
    {title:"White Winter Hymnal", artist:"Fleet Foxes", year:2008},
    {title:"Helplessness Blues", artist:"Fleet Foxes", year:2011},
    {title:"Mystery of Love", artist:"Sufjan Stevens", year:2017},
    {title:"Chicago", artist:"Sufjan Stevens", year:2005},
    {title:"Heather", artist:"Conan Gray", year:2020},
    {title:"Maniac", artist:"Conan Gray", year:2020},
    {title:"Sofia", artist:"Clairo", year:2019},
    {title:"Pretty Girl", artist:"Clairo", year:2017},
    {title:"Loving Is Easy", artist:"Rex Orange County", year:2017},
    {title:"Best Friend", artist:"Rex Orange County", year:2020},
    {title:"Death Bed", artist:"beabadoobee", year:2020},
    {title:"Talk", artist:"beabadoobee", year:2019},
    {title:"Are You Bored Yet?", artist:"Wallows", year:2019},
    {title:"Goodie Bag", artist:"Still Woozy", year:2018},
    {title:"3 Nights", artist:"Dominic Fike", year:2018},
    {title:"Evergreen", artist:"Omar Apollo", year:2022},
    {title:"Anchor", artist:"Novo Amor", year:2017},
    {title:"Heartbeats", artist:"Jose Gonzalez", year:2003},
    {title:"Between the Bars", artist:"Elliott Smith", year:1997},
    {title:"Miss Misery", artist:"Elliott Smith", year:1997},
    {title:"Naked as We Came", artist:"Iron & Wine", year:2004},
    {title:"Let Her Go", artist:"Passenger", year:2012},
    {title:"Say You Won't Let Go", artist:"James Arthur", year:2016},
    {title:"Common People", artist:"Pulp", year:1995},
    {title:"Fake Plastic Trees", artist:"Radiohead", year:1995},
    {title:"High and Dry", artist:"Radiohead", year:1995},
    {title:"Astrovan", artist:"Mt. Joy", year:2017},
    {title:"Silver Lining", artist:"Mt. Joy", year:2018},
    {title:"This Is Home", artist:"Cavetown", year:2018},
    {title:"Gooey", artist:"Glass Animals", year:2014},
    {title:"Youth", artist:"Glass Animals", year:2016},
    {title:"Way It Goes", artist:"Hippo Campus", year:2017},
    {title:"Buttercup", artist:"Hippo Campus", year:2017},
    {title:"prom dress", artist:"mxmtoon", year:2019},
    {title:"Coffee for Your Head", artist:"Powfu", year:2020},
    {title:"The Night Will Always Win", artist:"Manchester Orchestra", year:2011},
    {title:"The Great Pretender", artist:"The Beach Boys", year:1963},
    {title:"Sulfur", artist:"Slipknot", year:2008},
    {title:"Ocean", artist:"Frank Ocean", year:2016},
    {title:"2:00 AM", artist:"beabadoobee", year:2022},
    {title:"Face to Face", artist:"Rex Orange County", year:2021},
  ]},

  country: {label:"Country", songs:[
    {title:"Last Night", artist:"Morgan Wallen", year:2023},
    {title:"Whiskey Glasses", artist:"Morgan Wallen", year:2018},
    {title:"More Than My Hometown", artist:"Morgan Wallen", year:2020},
    {title:"Sand in My Boots", artist:"Morgan Wallen", year:2020},
    {title:"Wasted on You", artist:"Morgan Wallen", year:2021},
    {title:"7 Summers", artist:"Morgan Wallen", year:2020},
    {title:"Thought You Should Know", artist:"Morgan Wallen", year:2023},
    {title:"Something in the Orange", artist:"Zach Bryan", year:2022},
    {title:"I Remember Everything", artist:"Zach Bryan", year:2023},
    {title:"Heading South", artist:"Zach Bryan", year:2019},
    {title:"Revival", artist:"Zach Bryan", year:2021},
    {title:"Dawns", artist:"Zach Bryan", year:2023},
    {title:"Overtime", artist:"Zach Bryan", year:2022},
    {title:"I've Been Sober", artist:"Zach Bryan", year:2022},
    {title:"Beautiful Crazy", artist:"Luke Combs", year:2017},
    {title:"When It Rains It Pours", artist:"Luke Combs", year:2017},
    {title:"Beer Never Broke My Heart", artist:"Luke Combs", year:2019},
    {title:"Even Though I'm Leaving", artist:"Luke Combs", year:2019},
    {title:"Better Together", artist:"Luke Combs", year:2020},
    {title:"Forever After All", artist:"Luke Combs", year:2020},
    {title:"The Kind of Love We Make", artist:"Luke Combs", year:2022},
    {title:"What Ifs", artist:"Kane Brown", year:2016},
    {title:"Heaven", artist:"Kane Brown", year:2018},
    {title:"Good as You", artist:"Kane Brown", year:2019},
    {title:"Worldwide Beautiful", artist:"Kane Brown", year:2020},
    {title:"One Mississippi", artist:"Kane Brown", year:2016},
    {title:"Tennessee Whiskey", artist:"Chris Stapleton", year:2015},
    {title:"Broken Halos", artist:"Chris Stapleton", year:2017},
    {title:"Starting Over", artist:"Chris Stapleton", year:2020},
    {title:"Cold", artist:"Chris Stapleton", year:2015},
    {title:"Before He Cheats", artist:"Carrie Underwood", year:2005},
    {title:"Jesus Take the Wheel", artist:"Carrie Underwood", year:2005},
    {title:"Blown Away", artist:"Carrie Underwood", year:2012},
    {title:"God's Country", artist:"Blake Shelton", year:2019},
    {title:"God Gave Me You", artist:"Blake Shelton", year:2011},
    {title:"Country Girl (Shake It for Me)", artist:"Luke Bryan", year:2011},
    {title:"Play It Again", artist:"Luke Bryan", year:2013},
    {title:"Drunk on You", artist:"Luke Bryan", year:2011},
    {title:"Cruise", artist:"Florida Georgia Line", year:2012},
    {title:"This Is How We Roll", artist:"Florida Georgia Line", year:2013},
    {title:"Meant to Be", artist:"Bebe Rexha", year:2017},
    {title:"Die a Happy Man", artist:"Thomas Rhett", year:2015},
    {title:"Craving You", artist:"Thomas Rhett", year:2016},
    {title:"Life Changes", artist:"Thomas Rhett", year:2017},
    {title:"Remember You Young", artist:"Thomas Rhett", year:2019},
    {title:"Body Like a Back Road", artist:"Sam Hunt", year:2017},
    {title:"Leave the Night On", artist:"Sam Hunt", year:2014},
    {title:"House Party", artist:"Sam Hunt", year:2014},
    {title:"Tequila", artist:"Dan + Shay", year:2018},
    {title:"Speechless", artist:"Dan + Shay", year:2018},
    {title:"10,000 Hours", artist:"Dan + Shay", year:2019},
    {title:"Blue Ain't Your Color", artist:"Keith Urban", year:2016},
    {title:"My Church", artist:"Maren Morris", year:2016},
    {title:"Girl", artist:"Maren Morris", year:2019},
    {title:"I Hope", artist:"Gabby Barrett", year:2019},
    {title:"The Good Ones", artist:"Gabby Barrett", year:2020},
    {title:"Son of a Sinner", artist:"Jelly Roll", year:2022},
    {title:"Need a Favor", artist:"Jelly Roll", year:2023},
    {title:"Halfway to Hell", artist:"Jelly Roll", year:2022},
    {title:"Fall in Love", artist:"Bailey Zimmermann", year:2022},
    {title:"Rock and a Hard Place", artist:"Bailey Zimmermann", year:2023},
    {title:"Til You Can't", artist:"Cody Johnson", year:2021},
    {title:"Pretty Heart", artist:"Parker McCollum", year:2020},
    {title:"Things a Man Oughta Know", artist:"Lainey Wilson", year:2021},
    {title:"Heart Like a Truck", artist:"Lainey Wilson", year:2022},
    {title:"Five More Minutes", artist:"Scotty McCreery", year:2017},
    {title:"Singles You Up", artist:"Jordan Davis", year:2017},
    {title:"Dirt on My Boots", artist:"Jon Pardi", year:2016},
    {title:"Fancy Like", artist:"Walker Hayes", year:2021},
    {title:"Make It Sweet", artist:"Old Dominion", year:2019},
    {title:"One Man Band", artist:"Old Dominion", year:2019},
    {title:"One Beer", artist:"Hardy", year:2019},
    {title:"Chicken Fried", artist:"Zac Brown Band", year:2008},
    {title:"Toes", artist:"Zac Brown Band", year:2009},
    {title:"Drink in My Hand", artist:"Eric Church", year:2013},
    {title:"Live Like You Were Dying", artist:"Tim McGraw", year:2004},
    {title:"Humble and Kind", artist:"Tim McGraw", year:2016},
    {title:"American Kids", artist:"Kenny Chesney", year:2014},
    {title:"Then", artist:"Brad Paisley", year:2009},
    {title:"Dibs", artist:"Kelsea Ballerini", year:2015},
    {title:"Peter Pan", artist:"Kelsea Ballerini", year:2016},
    {title:"Drunk Me", artist:"Mitchell Tenpenny", year:2018},
    {title:"Every Little Thing", artist:"Carly Pearce", year:2017},
    {title:"Wagon Wheel", artist:"Darius Rucker", year:2013},
    {title:"Jolene", artist:"Dolly Parton", year:1973},
    {title:"9 to 5", artist:"Dolly Parton", year:1980},
    {title:"Ring of Fire", artist:"Johnny Cash", year:1963},
    {title:"Hurt", artist:"Johnny Cash", year:2002},
    {title:"Man in Black", artist:"Johnny Cash", year:1971},
    {title:"Friends in Low Places", artist:"Garth Brooks", year:1990},
    {title:"The Dance", artist:"Garth Brooks", year:1989},
    {title:"Man! I Feel Like a Woman!", artist:"Shania Twain", year:1999},
    {title:"You're Still the One", artist:"Shania Twain", year:1997},
    {title:"That Don't Impress Me Much", artist:"Shania Twain", year:1997},
    {title:"Chattahoochee", artist:"Alan Jackson", year:1992},
    {title:"Amarillo by Morning", artist:"George Strait", year:1982},
    {title:"The Gambler", artist:"Kenny Rogers", year:1978},
    {title:"Courtesy of the Red, White and Blue", artist:"Toby Keith", year:2002},
    {title:"Your Man", artist:"Josh Turner", year:2004},
    {title:"Beautiful Day", artist:"Joshua Radin", year:2008},
    {title:"Don't Come Lookin'", artist:"Jackson Dean", year:2021},
    {title:"Dancin' in the Country", artist:"Tyler Hubbard", year:2021},
  ]},

};

// Flat array for any legacy code
const SONGS = Object.values(GENRES).flatMap(g => g.songs);
