// GROUPLOCK — puzzle data
// categories ordered easiest (yellow) → hardest (purple)
// color values: 'yellow','green','blue','purple'

const PUZZLES = [
  {categories:[
    {label:"Things in a kitchen", color:"yellow", items:["Spatula","Whisk","Colander","Ladle"]},
    {label:"___ ball", color:"green", items:["Fire","Snow","Basket","Cannon"]},
    {label:"Taylor Swift albums", color:"blue", items:["Folklore","Fearless","Midnights","Evermore"]},
    {label:"Words that follow 'over'", color:"purple", items:["Come","Turn","Look","Load"]},
  ]},
  {categories:[
    {label:"Breakfast foods", color:"yellow", items:["Waffle","Bagel","Granola","Muffin"]},
    {label:"Types of cloud", color:"green", items:["Cirrus","Cumulus","Stratus","Nimbus"]},
    {label:"Bond films", color:"blue", items:["Skyfall","Casino","Spectre","Goldeneye"]},
    {label:"___ stone", color:"purple", items:["Key","Lime","Sand","Cobble"]},
  ]},
  {categories:[
    {label:"Pizza toppings", color:"yellow", items:["Pepperoni","Mushroom","Anchovy","Jalapeño"]},
    {label:"Famous Davids", color:"green", items:["Beckham","Bowie","Attenborough","Letterman"]},
    {label:"Types of bridge", color:"blue", items:["Suspension","Cable-stayed","Arch","Truss"]},
    {label:"Words before 'house'", color:"purple", items:["Green","Power","Fire","Tree"]},
  ]},
  {categories:[
    {label:"Dog breeds", color:"yellow", items:["Beagle","Poodle","Mastiff","Whippet"]},
    {label:"Cocktail ingredients", color:"green", items:["Vermouth","Grenadine","Bitters","Cointreau"]},
    {label:"Planets with rings", color:"blue", items:["Saturn","Uranus","Neptune","Jupiter"]},
    {label:"___ fish", color:"purple", items:["Sword","Cat","Angel","Blow"]},
  ]},
  {categories:[
    {label:"Card games", color:"yellow", items:["Snap","Rummy","Pontoon","Canasta"]},
    {label:"Types of pasta", color:"green", items:["Penne","Rigatoni","Fusilli","Farfalle"]},
    {label:"African capitals", color:"blue", items:["Nairobi","Accra","Dakar","Harare"]},
    {label:"Words after 'butter'", color:"purple", items:["Cup","Fly","Milk","Fingers"]},
  ]},
  {categories:[
    {label:"Olympic sports", color:"yellow", items:["Luge","Bobsled","Curling","Biathlon"]},
    {label:"Shades of blue", color:"green", items:["Cobalt","Cerulean","Indigo","Teal"]},
    {label:"Harry Potter characters", color:"blue", items:["Dumbledore","Snape","Draco","Lupin"]},
    {label:"___ work", color:"purple", items:["Net","Frame","Over","Team"]},
  ]},
  {categories:[
    {label:"Things in a bathroom", color:"yellow", items:["Loofah","Towel","Faucet","Grout"]},
    {label:"Famous Johns", color:"green", items:["Lennon","Wayne","Cleese","Steinbeck"]},
    {label:"Types of cheese", color:"blue", items:["Gouda","Gruyere","Manchego","Havarti"]},
    {label:"Words before 'light'", color:"purple", items:["Flash","Moon","Candle","Star"]},
  ]},
  {categories:[
    {label:"Board games", color:"yellow", items:["Cluedo","Othello","Pandemic","Scrabble"]},
    {label:"Things on a ship", color:"green", items:["Porthole","Mast","Helm","Keel"]},
    {label:"Shakespeare plays", color:"blue", items:["Othello","Macbeth","Prospero","Oberon"]},
    {label:"___ bar", color:"purple", items:["Crow","Space","Mini","Handle"]},
  ]},
  {categories:[
    {label:"Types of tree", color:"yellow", items:["Birch","Willow","Sequoia","Banyan"]},
    {label:"Famous Marys", color:"green", items:["Shelley","Poppins","Berry","Beard"]},
    {label:"Elements that are gases at room temp", color:"blue", items:["Helium","Neon","Argon","Krypton"]},
    {label:"Words that follow 'black'", color:"purple", items:["Bird","Berry","Out","Board"]},
  ]},
  {categories:[
    {label:"Types of hat", color:"yellow", items:["Beret","Fedora","Stetson","Trilby"]},
    {label:"Fast food chains", color:"green", items:["Wendy's","Chick-fil-A","Arby's","Sonic"]},
    {label:"Classical composers", color:"blue", items:["Vivaldi","Debussy","Brahms","Schubert"]},
    {label:"___ court", color:"purple", items:["Short","Food","Tennis","Royal"]},
  ]},
  {categories:[
    {label:"Vegetables", color:"yellow", items:["Kohlrabi","Parsnip","Turnip","Celeriac"]},
    {label:"Types of dance", color:"green", items:["Foxtrot","Merengue","Lindy Hop","Quickstep"]},
    {label:"US state capitals", color:"blue", items:["Austin","Juneau","Boise","Topeka"]},
    {label:"Words after 'sea'", color:"purple", items:["Horse","Shell","Weed","Gull"]},
  ]},
  {categories:[
    {label:"Cuts of beef", color:"yellow", items:["Brisket","Sirloin","Ribeye","Flank"]},
    {label:"Famous Queens", color:"green", items:["Victoria","Cleopatra","Nefertiti","Boudicca"]},
    {label:"Types of bridge (card game)", color:"blue", items:["Duplicate","Contract","Rubber","Chicago"]},
    {label:"___ line", color:"purple", items:["Hair","Land","Dead","Base"]},
  ]},
  {categories:[
    {label:"Fruits", color:"yellow", items:["Lychee","Papaya","Guava","Rambutan"]},
    {label:"Dances from the 50s/60s", color:"green", items:["Twist","Jive","Mashed Potato","Watusi"]},
    {label:"Greek gods", color:"blue", items:["Hermes","Ares","Dionysus","Hephaestus"]},
    {label:"Words before 'back'", color:"purple", items:["Set","Draw","Play","Come"]},
  ]},
  {categories:[
    {label:"Types of noodle", color:"yellow", items:["Udon","Soba","Vermicelli","Ramen"]},
    {label:"UK prime ministers", color:"green", items:["Blair","Thatcher","Attlee","Callaghan"]},
    {label:"Marvel superheroes", color:"blue", items:["Wolverine","Cyclops","Storm","Colossus"]},
    {label:"___ ring", color:"purple", items:["Box","Ear","Teething","Circus"]},
  ]},
  {categories:[
    {label:"Musical instruments", color:"yellow", items:["Dulcimer","Zither","Sousaphone","Hurdy-gurdy"]},
    {label:"Types of steak", color:"green", items:["T-bone","Porterhouse","Wagyu","Hanger"]},
    {label:"Cartoon dogs", color:"blue", items:["Pluto","Goofy","Scooby","Snoopy"]},
    {label:"Words after 'eye'", color:"purple", items:["Brow","Lash","Lid","Brow"]},
  ]},
  {categories:[
    {label:"Things at a campsite", color:"yellow", items:["Kindling","Hammock","Lantern","Tarpaulin"]},
    {label:"Types of boat", color:"green", items:["Catamaran","Skiff","Galleon","Dinghy"]},
    {label:"Famous Elizabeths", color:"blue", items:["Warren","Taylor","Bennet","Swann"]},
    {label:"___ cap", color:"purple", items:["Hub","Kneecap","Ice","Nightcap"]},
  ]},
  {categories:[
    {label:"Types of coffee", color:"yellow", items:["Ristretto","Macchiato","Cortado","Affogato"]},
    {label:"Bones in the body", color:"green", items:["Femur","Tibia","Ulna","Sternum"]},
    {label:"Famous Amys", color:"blue", items:["Winehouse","Schumer","Adams","Lee"]},
    {label:"Words before 'fall'", color:"purple", items:["Water","Down","Free","Night"]},
  ]},
  {categories:[
    {label:"Types of cloud computing", color:"yellow", items:["SaaS","PaaS","IaaS","FaaS"]},
    {label:"Cocktails", color:"green", items:["Sidecar","Gimlet","Negroni","Daiquiri"]},
    {label:"Dinosaurs", color:"blue", items:["Brachiosaurus","Ankylosaurus","Spinosaurus","Diplodocus"]},
    {label:"___ point", color:"purple", items:["Gun","Ball","Match","Flash"]},
  ]},
  {categories:[
    {label:"Things you find on a farm", color:"yellow", items:["Trough","Bale","Silo","Furrow"]},
    {label:"Types of currency", color:"green", items:["Zloty","Forint","Dirham","Baht"]},
    {label:"Operas", color:"blue", items:["Tosca","Rigoletto","Aida","Norma"]},
    {label:"Words after 'sun'", color:"purple", items:["Burn","Flower","Rise","Stroke"]},
  ]},
  {categories:[
    {label:"Things in an office", color:"yellow", items:["Stapler","Binder","Inbox","Shredder"]},
    {label:"Types of volcano", color:"green", items:["Shield","Cinder","Composite","Caldera"]},
    {label:"Dickens characters", color:"blue", items:["Fagin","Micawber","Squeers","Gradgrind"]},
    {label:"___ side", color:"purple", items:["Out","Down","Under","Blind"]},
  ]},
  {categories:[
    {label:"Ice cream flavours", color:"yellow", items:["Pistachio","Praline","Stracciatella","Cassata"]},
    {label:"Things in space", color:"green", items:["Quasar","Nebula","Pulsar","Magnetar"]},
    {label:"Famous Williams", color:"blue", items:["Shakespeare","Wordsworth","Blake","Keats"]},
    {label:"Words before 'stone'", color:"purple", items:["Key","Sand","Lime","Cobble"]},
  ]},
  {categories:[
    {label:"Things you wear on your feet", color:"yellow", items:["Moccasin","Clog","Espadrille","Sabot"]},
    {label:"Types of shark", color:"green", items:["Hammerhead","Mako","Lemon","Thresher"]},
    {label:"Famous Charlies", color:"blue", items:["Chaplin","Darwin","Sheen","Kaufman"]},
    {label:"___ point", color:"purple", items:["Sword","Stand","Power","Ball"]},
  ]},
  {categories:[
    {label:"Spices", color:"yellow", items:["Cardamom","Fenugreek","Sumac","Asafoetida"]},
    {label:"Things in a forest", color:"green", items:["Canopy","Lichen","Undergrowth","Burrow"]},
    {label:"TV detectives", color:"blue", items:["Columbo","Morse","Poirot","Wallander"]},
    {label:"Words after 'over'", color:"purple", items:["Come","Board","Cast","Haul"]},
  ]},
  {categories:[
    {label:"Types of bread", color:"yellow", items:["Ciabatta","Brioche","Focaccia","Sourdough"]},
    {label:"Swimming strokes", color:"green", items:["Butterfly","Breaststroke","Crawl","Backstroke"]},
    {label:"Countries in Scandinavia", color:"blue", items:["Sweden","Norway","Denmark","Finland"]},
    {label:"___ drop", color:"purple", items:["Dew","Tear","Back","Name"]},
  ]},
  {categories:[
    {label:"Things at a carnival", color:"yellow", items:["Helter-skelter","Dodgem","Tombola","Waltzer"]},
    {label:"Types of poem", color:"green", items:["Sonnet","Haiku","Limerick","Villanelle"]},
    {label:"Bond girls", color:"blue", items:["Moneypenny","Vesper","Nomi","Holly"]},
    {label:"Words before 'time'", color:"purple", items:["Over","Bed","Half","Day"]},
  ]},
  {categories:[
    {label:"Things you'd find in a forest", color:"yellow", items:["Acorn","Fern","Moss","Badger"]},
    {label:"Types of sauce", color:"green", items:["Béchamel","Hollandaise","Velouté","Espagnole"]},
    {label:"Famous Georges", color:"blue", items:["Orwell","Clooney","Harrison","Carlin"]},
    {label:"___ field", color:"purple", items:["Coal","Mine","Oil","Corn"]},
  ]},
  {categories:[
    {label:"Types of neckwear", color:"yellow", items:["Cravat","Ascot","Jabot","Stock"]},
    {label:"Things in a river", color:"green", items:["Current","Eddy","Riffle","Weir"]},
    {label:"Famous Bobs", color:"blue", items:["Dylan","Hope","Marley","De Niro"]},
    {label:"Words after 'under'", color:"purple", items:["Cover","World","Tone","Dog"]},
  ]},
  {categories:[
    {label:"Types of cheese (French)", color:"yellow", items:["Brie","Camembert","Roquefort","Comté"]},
    {label:"Constellations", color:"green", items:["Orion","Cassiopeia","Lyra","Perseus"]},
    {label:"Famous Mikes", color:"blue", items:["Tyson","Jordan","Jagger","Tyson"]},
    {label:"___ base", color:"purple", items:["Home","Air","Data","Knowledge"]},
  ]},
  {categories:[
    {label:"Gym equipment", color:"yellow", items:["Kettlebell","Barbell","Dumbbell","Medicine ball"]},
    {label:"Types of eclipse", color:"green", items:["Total","Partial","Annular","Hybrid"]},
    {label:"Roald Dahl books", color:"blue", items:["Matilda","Danny","Fantastic","Esio"]},
    {label:"Words before 'cake'", color:"purple", items:["Cheese","Cup","Pan","Short"]},
  ]},
  {categories:[
    {label:"Things on a chessboard", color:"yellow", items:["Bishop","Castle","Knight","Pawn"]},
    {label:"Types of cloud (weather)", color:"green", items:["Altocumulus","Lenticular","Mammatus","Nacreous"]},
    {label:"Famous Stephens", color:"blue", items:["Fry","Spielberg","King","Hawking"]},
    {label:"___ run", color:"purple", items:["Dry","Bull","Home","Ski"]},
  ]},
  {categories:[
    {label:"Types of soil", color:"yellow", items:["Loam","Clay","Silt","Peat"]},
    {label:"TV sitcoms", color:"green", items:["Frasier","Cheers","Seinfeld","Taxi"]},
    {label:"Famous Kates", color:"blue", items:["Bush","Blanchett","Winslet","Moss"]},
    {label:"Words before 'board'", color:"purple", items:["Skate","Card","Key","Surf"]},
  ]},
  {categories:[
    {label:"Types of fabric", color:"yellow", items:["Muslin","Cambric","Organza","Grosgrain"]},
    {label:"Things in a pub", color:"green", items:["Jukebox","Optic","Snug","Dart board"]},
    {label:"Famous Nicks", color:"blue", items:["Cave","Jonas","Offerman","Grimshaw"]},
    {label:"___ well", color:"purple", items:["Fare","Ink","Stair","Pump"]},
  ]},
  {categories:[
    {label:"Types of pasta shape", color:"yellow", items:["Conchiglie","Orecchiette","Gemelli","Paccheri"]},
    {label:"Things in a gym locker room", color:"green", items:["Shampoo","Padlock","Flip-flops","Towel hook"]},
    {label:"Fonts", color:"blue", items:["Helvetica","Garamond","Futura","Palatino"]},
    {label:"Words after 'short'", color:"purple", items:["Cut","Fall","List","Change"]},
  ]},
  {categories:[
    {label:"Things at a wedding", color:"yellow", items:["Corsage","Tiara","Boutonnière","Garter"]},
    {label:"Types of stitch", color:"green", items:["Cross","Chain","Satin","Running"]},
    {label:"Famous Pauls", color:"blue", items:["McCartney","Newman","Simon","Weller"]},
    {label:"___ key", color:"purple", items:["Mon","Don","Tur","Mon"]},
  ]},
  {categories:[
    {label:"Things in a supermarket", color:"yellow", items:["Trolley","Barcode","Aisle","Checkout"]},
    {label:"Types of tea", color:"green", items:["Darjeeling","Oolong","Matcha","Rooibos"]},
    {label:"Famous Johns", color:"blue", items:["Keats","Donne","Milton","Dryden"]},
    {label:"Words before 'pepper'", color:"purple", items:["Red","Black","Bell","Chilli"]},
  ]},
  {categories:[
    {label:"Types of wine", color:"yellow", items:["Viognier","Grenache","Tempranillo","Carménère"]},
    {label:"Things in a library", color:"green", items:["Catalogue","Microfiche","Periodical","Stacks"]},
    {label:"Famous Annas", color:"blue", items:["Karenina","Wintour","Frank","Magnani"]},
    {label:"___ cover", color:"purple", items:["Under","Hard","Ground","Soft"]},
  ]},
  {categories:[
    {label:"Types of knot", color:"yellow", items:["Bowline","Clove hitch","Sheet bend","Reef"]},
    {label:"Things that glow", color:"green", items:["Bioluminescence","Phosphorescence","Aurora","Neon"]},
    {label:"90s boy bands", color:"blue", items:["Hanson","98 Degrees","LFO","O-Town"]},
    {label:"Words before 'smith'", color:"purple", items:["Black","Gold","Silver","Lock"]},
  ]},
  {categories:[
    {label:"Types of yoga", color:"yellow", items:["Ashtanga","Vinyasa","Kundalini","Iyengar"]},
    {label:"Things on a beach", color:"green", items:["Groyne","Dune","Breakwater","Estuary"]},
    {label:"Famous Marks", color:"blue", items:["Twain","Zuckerberg","Ronson","Wahlberg"]},
    {label:"___ gate", color:"purple", items:["Iron","Flood","Tail","Flap"]},
  ]},
  {categories:[
    {label:"Types of nut", color:"yellow", items:["Macadamia","Pistachio","Hazelnut","Pecan"]},
    {label:"Things in a chemistry lab", color:"green", items:["Burette","Pipette","Crucible","Spatula"]},
    {label:"Famous Elijahs", color:"blue", items:["Wood","Muhammad","Blue","Burke"]},
    {label:"Words after 'gun'", color:"purple", items:["Fire","Shot","Powder","Smoke"]},
  ]},
  {categories:[
    {label:"Collective nouns for animals", color:"yellow", items:["Murder","Parliament","Crash","Bloat"]},
    {label:"Cocktails with rum", color:"green", items:["Mojito","Daiquiri","Hurricane","Planter's Punch"]},
    {label:"Famous Davids (musicians)", color:"blue", items:["Bowie","Byrne","Gilmour","Grohl"]},
    {label:"___ man", color:"purple", items:["Spider","Iron","Pac","Snow"]},
  ]},
  {categories:[
    {label:"Things you find in a wallet", color:"yellow", items:["Loyalty card","Receipt","Coin","Note"]},
    {label:"Types of column (architecture)", color:"green", items:["Doric","Ionic","Corinthian","Tuscan"]},
    {label:"Famous Eds", color:"blue", items:["Sheeran","Balls","Miliband","Sheeran"]},
    {label:"Words before 'house'", color:"purple", items:["Ale","Open","Ware","Rough"]},
  ]},
];
