// LENSLOCK — data for all three tabs
// CoverLock: {title, artist}
// FlagLock:  {name, code (ISO 3166-1 alpha-2), continent, region}
// LogoLock:  {name, domain, category}

// ============================================
// TAB 1: COVER — album art via iTunes API
// ============================================
const COVER_SONGS = [
    {title:"Blinding Lights",artist:"The Weeknd"},
    {title:"Shape of You",artist:"Ed Sheeran"},
    {title:"Dance Monkey",artist:"Tones and I"},
    {title:"Stay",artist:"The Kid LAROI"},
    {title:"Levitating",artist:"Dua Lipa"},
    {title:"drivers license",artist:"Olivia Rodrigo"},
    {title:"Watermelon Sugar",artist:"Harry Styles"},
    {title:"good 4 u",artist:"Olivia Rodrigo"},
    {title:"Heat Waves",artist:"Glass Animals"},
    {title:"Easy On Me",artist:"Adele"},
    {title:"As It Was",artist:"Harry Styles"},
    {title:"Anti-Hero",artist:"Taylor Swift"},
    {title:"Flowers",artist:"Miley Cyrus"},
    {title:"Cruel Summer",artist:"Taylor Swift"},
    {title:"Kill Bill",artist:"SZA"},
    {title:"Unholy",artist:"Sam Smith"},
    {title:"Save Your Tears",artist:"The Weeknd"},
    {title:"Bad Guy",artist:"Billie Eilish"},
    {title:"Montero",artist:"Lil Nas X"},
    {title:"Sunflower",artist:"Post Malone"},
    {title:"Sign of the Times",artist:"Harry Styles"},
    {title:"Cardigan",artist:"Taylor Swift"},
    {title:"Shake It Off",artist:"Taylor Swift"},
    {title:"Blank Space",artist:"Taylor Swift"},
    {title:"All Too Well",artist:"Taylor Swift"},
    {title:"Ocean Eyes",artist:"Billie Eilish"},
    {title:"What Was I Made For",artist:"Billie Eilish"},
    {title:"Can't Feel My Face",artist:"The Weeknd"},
    {title:"Starboy",artist:"The Weeknd"},
    {title:"God's Plan",artist:"Drake"},
    {title:"HUMBLE.",artist:"Kendrick Lamar"},
    {title:"Not Like Us",artist:"Kendrick Lamar"},
    {title:"Sicko Mode",artist:"Travis Scott"},
    {title:"Lucid Dreams",artist:"Juice WRLD"},
    {title:"The Box",artist:"Roddy Ricch"},
    {title:"Say So",artist:"Doja Cat"},
    {title:"Good Days",artist:"SZA"},
    {title:"Rockstar",artist:"Post Malone"},
    {title:"Circles",artist:"Post Malone"},
    {title:"Redbone",artist:"Childish Gambino"},
    {title:"This Is America",artist:"Childish Gambino"},
    {title:"In The End",artist:"Linkin Park"},
    {title:"Numb",artist:"Linkin Park"},
    {title:"Do I Wanna Know?",artist:"Arctic Monkeys"},
    {title:"Mr. Brightside",artist:"The Killers"},
    {title:"Welcome to the Black Parade",artist:"My Chemical Romance"},
    {title:"Sugar, We're Goin Down",artist:"Fall Out Boy"},
    {title:"Misery Business",artist:"Paramore"},
    {title:"Boulevard of Broken Dreams",artist:"Green Day"},
    {title:"Everlong",artist:"Foo Fighters"},
    {title:"Yellow",artist:"Coldplay"},
    {title:"Fix You",artist:"Coldplay"},
    {title:"Viva la Vida",artist:"Coldplay"},
    {title:"Madness",artist:"Muse"},
    {title:"Supermassive Black Hole",artist:"Muse"},
    {title:"Rehab",artist:"Amy Winehouse"},
    {title:"Back to Black",artist:"Amy Winehouse"},
    {title:"Take Me to Church",artist:"Hozier"},
    {title:"Summertime Sadness",artist:"Lana Del Rey"},
    {title:"The Less I Know the Better",artist:"Tame Impala"},
    {title:"Bohemian Rhapsody",artist:"Queen"},
    {title:"Don't Stop Me Now",artist:"Queen"},
    {title:"Billie Jean",artist:"Michael Jackson"},
    {title:"Thriller",artist:"Michael Jackson"},
    {title:"Smooth Criminal",artist:"Michael Jackson"},
    {title:"Smells Like Teen Spirit",artist:"Nirvana"},
    {title:"Stairway to Heaven",artist:"Led Zeppelin"},
    {title:"Another Brick in the Wall",artist:"Pink Floyd"},
    {title:"Comfortably Numb",artist:"Pink Floyd"},
    {title:"Hey Jude",artist:"The Beatles"},
    {title:"Come Together",artist:"The Beatles"},
    {title:"Back in Black",artist:"AC/DC"},
    {title:"Highway to Hell",artist:"AC/DC"},
    {title:"Enter Sandman",artist:"Metallica"},
    {title:"Sweet Child O' Mine",artist:"Guns N' Roses"},
    {title:"(I Can't Get No) Satisfaction",artist:"The Rolling Stones"},
    {title:"Hotel California",artist:"Eagles"},
    {title:"Purple Rain",artist:"Prince"},
    {title:"Heroes",artist:"David Bowie"},
    {title:"Rocket Man",artist:"Elton John"},
    {title:"In the Air Tonight",artist:"Phil Collins"},
    {title:"I Will Always Love You",artist:"Whitney Houston"},
    {title:"All I Want for Christmas Is You",artist:"Mariah Carey"},
    {title:"Dancing Queen",artist:"ABBA"},
    {title:"Mamma Mia",artist:"ABBA"},
    {title:"Rolling in the Deep",artist:"Adele"},
    {title:"Hello",artist:"Adele"},
    {title:"Someone Like You",artist:"Adele"},
    {title:"All of Me",artist:"John Legend"},
    {title:"Uptown Funk",artist:"Mark Ronson"},
    {title:"Happy",artist:"Pharrell Williams"},
    {title:"Despacito",artist:"Luis Fonsi"},
    {title:"Hips Don't Lie",artist:"Shakira"},
    {title:"Just The Way You Are",artist:"Bruno Mars"},
    {title:"24K Magic",artist:"Bruno Mars"},
    {title:"Thank U Next",artist:"Ariana Grande"},
    {title:"7 Rings",artist:"Ariana Grande"},
    {title:"Don't Start Now",artist:"Dua Lipa"},
    {title:"New Rules",artist:"Dua Lipa"},
    {title:"Bad Romance",artist:"Lady Gaga"},
    {title:"Poker Face",artist:"Lady Gaga"},
    {title:"Umbrella",artist:"Rihanna"},
    {title:"Diamonds",artist:"Rihanna"},
    {title:"We Found Love",artist:"Rihanna"},
    {title:"Sorry",artist:"Justin Bieber"},
    {title:"Love Yourself",artist:"Justin Bieber"},
    {title:"Baby",artist:"Justin Bieber"},
    {title:"Chandelier",artist:"Sia"},
    {title:"Cheap Thrills",artist:"Sia"},
    {title:"Closer",artist:"The Chainsmokers"},
    {title:"Levels",artist:"Avicii"},
    {title:"Wake Me Up",artist:"Avicii"},
    {title:"Get Lucky",artist:"Daft Punk"},
    {title:"One More Time",artist:"Daft Punk"},
    {title:"Lean On",artist:"Major Lazer"},
    {title:"Stay With Me",artist:"Sam Smith"},
    {title:"Lose Yourself",artist:"Eminem"},
    {title:"Stan",artist:"Eminem"},
    {title:"Gold Digger",artist:"Kanye West"},
    {title:"POWER",artist:"Kanye West"},
    {title:"Crazy In Love",artist:"Beyonce"},
    {title:"Halo",artist:"Beyonce"},
    {title:"Single Ladies",artist:"Beyonce"},
    {title:"California Gurls",artist:"Katy Perry"},
    {title:"Roar",artist:"Katy Perry"},
    {title:"Firework",artist:"Katy Perry"},
    {title:"Wrecking Ball",artist:"Miley Cyrus"},
    {title:"Stressed Out",artist:"Twenty One Pilots"},
    {title:"Believer",artist:"Imagine Dragons"},
    {title:"Radioactive",artist:"Imagine Dragons"},
    {title:"...Baby One More Time",artist:"Britney Spears"},
    {title:"Toxic",artist:"Britney Spears"},
    {title:"Wonderwall",artist:"Oasis"},
    {title:"Take On Me",artist:"a-ha"},
    {title:"Livin' on a Prayer",artist:"Bon Jovi"},
    {title:"Girls Just Wanna Have Fun",artist:"Cyndi Lauper"},
    {title:"Like a Prayer",artist:"Madonna"},
    {title:"Careless Whisper",artist:"George Michael"},
];

// ============================================
// TAB 2: FLAG — via flagcdn.com/w640/{code}.png
// ============================================
const FLAG_COUNTRIES = [
    {name:"United Kingdom",code:"gb",continent:"Europe",region:"Western Europe"},
    {name:"United States",code:"us",continent:"North America",region:"Northern America"},
    {name:"France",code:"fr",continent:"Europe",region:"Western Europe"},
    {name:"Germany",code:"de",continent:"Europe",region:"Western Europe"},
    {name:"Italy",code:"it",continent:"Europe",region:"Southern Europe"},
    {name:"Spain",code:"es",continent:"Europe",region:"Southern Europe"},
    {name:"Portugal",code:"pt",continent:"Europe",region:"Southern Europe"},
    {name:"Netherlands",code:"nl",continent:"Europe",region:"Western Europe"},
    {name:"Belgium",code:"be",continent:"Europe",region:"Western Europe"},
    {name:"Switzerland",code:"ch",continent:"Europe",region:"Western Europe"},
    {name:"Austria",code:"at",continent:"Europe",region:"Western Europe"},
    {name:"Sweden",code:"se",continent:"Europe",region:"Northern Europe"},
    {name:"Norway",code:"no",continent:"Europe",region:"Northern Europe"},
    {name:"Denmark",code:"dk",continent:"Europe",region:"Northern Europe"},
    {name:"Finland",code:"fi",continent:"Europe",region:"Northern Europe"},
    {name:"Iceland",code:"is",continent:"Europe",region:"Northern Europe"},
    {name:"Ireland",code:"ie",continent:"Europe",region:"Northern Europe"},
    {name:"Poland",code:"pl",continent:"Europe",region:"Eastern Europe"},
    {name:"Czech Republic",code:"cz",continent:"Europe",region:"Eastern Europe"},
    {name:"Hungary",code:"hu",continent:"Europe",region:"Eastern Europe"},
    {name:"Romania",code:"ro",continent:"Europe",region:"Eastern Europe"},
    {name:"Bulgaria",code:"bg",continent:"Europe",region:"Eastern Europe"},
    {name:"Croatia",code:"hr",continent:"Europe",region:"Southern Europe"},
    {name:"Serbia",code:"rs",continent:"Europe",region:"Southern Europe"},
    {name:"Greece",code:"gr",continent:"Europe",region:"Southern Europe"},
    {name:"Ukraine",code:"ua",continent:"Europe",region:"Eastern Europe"},
    {name:"Russia",code:"ru",continent:"Europe",region:"Eastern Europe"},
    {name:"Turkey",code:"tr",continent:"Asia",region:"Western Asia"},
    {name:"Canada",code:"ca",continent:"North America",region:"Northern America"},
    {name:"Mexico",code:"mx",continent:"North America",region:"Central America"},
    {name:"Brazil",code:"br",continent:"South America",region:"South America"},
    {name:"Argentina",code:"ar",continent:"South America",region:"South America"},
    {name:"Chile",code:"cl",continent:"South America",region:"South America"},
    {name:"Colombia",code:"co",continent:"South America",region:"South America"},
    {name:"Peru",code:"pe",continent:"South America",region:"South America"},
    {name:"Venezuela",code:"ve",continent:"South America",region:"South America"},
    {name:"Ecuador",code:"ec",continent:"South America",region:"South America"},
    {name:"Bolivia",code:"bo",continent:"South America",region:"South America"},
    {name:"Uruguay",code:"uy",continent:"South America",region:"South America"},
    {name:"Paraguay",code:"py",continent:"South America",region:"South America"},
    {name:"Australia",code:"au",continent:"Oceania",region:"Australasia"},
    {name:"New Zealand",code:"nz",continent:"Oceania",region:"Australasia"},
    {name:"Japan",code:"jp",continent:"Asia",region:"East Asia"},
    {name:"China",code:"cn",continent:"Asia",region:"East Asia"},
    {name:"South Korea",code:"kr",continent:"Asia",region:"East Asia"},
    {name:"India",code:"in",continent:"Asia",region:"South Asia"},
    {name:"Pakistan",code:"pk",continent:"Asia",region:"South Asia"},
    {name:"Bangladesh",code:"bd",continent:"Asia",region:"South Asia"},
    {name:"Indonesia",code:"id",continent:"Asia",region:"Southeast Asia"},
    {name:"Malaysia",code:"my",continent:"Asia",region:"Southeast Asia"},
    {name:"Thailand",code:"th",continent:"Asia",region:"Southeast Asia"},
    {name:"Vietnam",code:"vn",continent:"Asia",region:"Southeast Asia"},
    {name:"Philippines",code:"ph",continent:"Asia",region:"Southeast Asia"},
    {name:"Singapore",code:"sg",continent:"Asia",region:"Southeast Asia"},
    {name:"Saudi Arabia",code:"sa",continent:"Asia",region:"Western Asia"},
    {name:"Iran",code:"ir",continent:"Asia",region:"Western Asia"},
    {name:"Iraq",code:"iq",continent:"Asia",region:"Western Asia"},
    {name:"Israel",code:"il",continent:"Asia",region:"Western Asia"},
    {name:"United Arab Emirates",code:"ae",continent:"Asia",region:"Western Asia"},
    {name:"Qatar",code:"qa",continent:"Asia",region:"Western Asia"},
    {name:"Kazakhstan",code:"kz",continent:"Asia",region:"Central Asia"},
    {name:"Afghanistan",code:"af",continent:"Asia",region:"South Asia"},
    {name:"Sri Lanka",code:"lk",continent:"Asia",region:"South Asia"},
    {name:"Myanmar",code:"mm",continent:"Asia",region:"Southeast Asia"},
    {name:"Nepal",code:"np",continent:"Asia",region:"South Asia"},
    {name:"Egypt",code:"eg",continent:"Africa",region:"North Africa"},
    {name:"Morocco",code:"ma",continent:"Africa",region:"North Africa"},
    {name:"Algeria",code:"dz",continent:"Africa",region:"North Africa"},
    {name:"Tunisia",code:"tn",continent:"Africa",region:"North Africa"},
    {name:"Libya",code:"ly",continent:"Africa",region:"North Africa"},
    {name:"Sudan",code:"sd",continent:"Africa",region:"East Africa"},
    {name:"Ethiopia",code:"et",continent:"Africa",region:"East Africa"},
    {name:"Kenya",code:"ke",continent:"Africa",region:"East Africa"},
    {name:"Tanzania",code:"tz",continent:"Africa",region:"East Africa"},
    {name:"Uganda",code:"ug",continent:"Africa",region:"East Africa"},
    {name:"Nigeria",code:"ng",continent:"Africa",region:"West Africa"},
    {name:"Ghana",code:"gh",continent:"Africa",region:"West Africa"},
    {name:"Senegal",code:"sn",continent:"Africa",region:"West Africa"},
    {name:"Ivory Coast",code:"ci",continent:"Africa",region:"West Africa"},
    {name:"Cameroon",code:"cm",continent:"Africa",region:"Central Africa"},
    {name:"DR Congo",code:"cd",continent:"Africa",region:"Central Africa"},
    {name:"South Africa",code:"za",continent:"Africa",region:"Southern Africa"},
    {name:"Zimbabwe",code:"zw",continent:"Africa",region:"Southern Africa"},
    {name:"Mozambique",code:"mz",continent:"Africa",region:"Southern Africa"},
    {name:"Madagascar",code:"mg",continent:"Africa",region:"East Africa"},
    {name:"Somalia",code:"so",continent:"Africa",region:"East Africa"},
    {name:"Cuba",code:"cu",continent:"North America",region:"Caribbean"},
    {name:"Jamaica",code:"jm",continent:"North America",region:"Caribbean"},
    {name:"Haiti",code:"ht",continent:"North America",region:"Caribbean"},
    {name:"Dominican Republic",code:"do",continent:"North America",region:"Caribbean"},
    {name:"Guatemala",code:"gt",continent:"North America",region:"Central America"},
    {name:"Honduras",code:"hn",continent:"North America",region:"Central America"},
    {name:"Costa Rica",code:"cr",continent:"North America",region:"Central America"},
    {name:"Panama",code:"pa",continent:"North America",region:"Central America"},
    {name:"Mongolia",code:"mn",continent:"Asia",region:"East Asia"},
    {name:"North Korea",code:"kp",continent:"Asia",region:"East Asia"},
    {name:"Cambodia",code:"kh",continent:"Asia",region:"Southeast Asia"},
    {name:"Laos",code:"la",continent:"Asia",region:"Southeast Asia"},
    {name:"Papua New Guinea",code:"pg",continent:"Oceania",region:"Melanesia"},
    {name:"Fiji",code:"fj",continent:"Oceania",region:"Melanesia"},
    {name:"Jordan",code:"jo",continent:"Asia",region:"Western Asia"},
    {name:"Lebanon",code:"lb",continent:"Asia",region:"Western Asia"},
    {name:"Syria",code:"sy",continent:"Asia",region:"Western Asia"},
    {name:"Yemen",code:"ye",continent:"Asia",region:"Western Asia"},
    {name:"Oman",code:"om",continent:"Asia",region:"Western Asia"},
    {name:"Kuwait",code:"kw",continent:"Asia",region:"Western Asia"},
    {name:"Bahrain",code:"bh",continent:"Asia",region:"Western Asia"},
    {name:"Georgia",code:"ge",continent:"Asia",region:"Western Asia"},
    {name:"Armenia",code:"am",continent:"Asia",region:"Western Asia"},
    {name:"Azerbaijan",code:"az",continent:"Asia",region:"Western Asia"},
];

// ============================================
// TAB 3: LOGO — via logo.clearbit.com/{domain}
// ============================================
const LOGO_BRANDS = [
    // Technology
    {name:"Apple",domain:"apple.com",category:"Technology"},
    {name:"Google",domain:"google.com",category:"Technology"},
    {name:"Microsoft",domain:"microsoft.com",category:"Technology"},
    {name:"Amazon",domain:"amazon.com",category:"Technology"},
    {name:"Meta",domain:"meta.com",category:"Technology"},
    {name:"Netflix",domain:"netflix.com",category:"Technology"},
    {name:"Spotify",domain:"spotify.com",category:"Technology"},
    {name:"YouTube",domain:"youtube.com",category:"Technology"},
    {name:"Samsung",domain:"samsung.com",category:"Technology"},
    {name:"Sony",domain:"sony.com",category:"Technology"},
    {name:"Intel",domain:"intel.com",category:"Technology"},
    {name:"NVIDIA",domain:"nvidia.com",category:"Technology"},
    {name:"Adobe",domain:"adobe.com",category:"Technology"},
    {name:"Airbnb",domain:"airbnb.com",category:"Technology"},
    {name:"Uber",domain:"uber.com",category:"Technology"},
    {name:"Snapchat",domain:"snapchat.com",category:"Technology"},
    {name:"Discord",domain:"discord.com",category:"Technology"},
    {name:"LinkedIn",domain:"linkedin.com",category:"Technology"},
    {name:"PayPal",domain:"paypal.com",category:"Technology"},
    {name:"Twitter",domain:"twitter.com",category:"Technology"},
    {name:"Zoom",domain:"zoom.us",category:"Technology"},
    {name:"Shopify",domain:"shopify.com",category:"Technology"},
    {name:"Stripe",domain:"stripe.com",category:"Technology"},
    {name:"Dropbox",domain:"dropbox.com",category:"Technology"},
    {name:"TikTok",domain:"tiktok.com",category:"Technology"},
    {name:"Twitch",domain:"twitch.tv",category:"Technology"},
    {name:"Reddit",domain:"reddit.com",category:"Technology"},
    {name:"Pinterest",domain:"pinterest.com",category:"Technology"},
    // Food & Drink
    {name:"McDonald's",domain:"mcdonalds.com",category:"Food & Drink"},
    {name:"Starbucks",domain:"starbucks.com",category:"Food & Drink"},
    {name:"Coca-Cola",domain:"coca-cola.com",category:"Food & Drink"},
    {name:"Pepsi",domain:"pepsi.com",category:"Food & Drink"},
    {name:"KFC",domain:"kfc.com",category:"Food & Drink"},
    {name:"Subway",domain:"subway.com",category:"Food & Drink"},
    {name:"Domino's",domain:"dominos.com",category:"Food & Drink"},
    {name:"Pizza Hut",domain:"pizzahut.com",category:"Food & Drink"},
    {name:"Burger King",domain:"burgerking.com",category:"Food & Drink"},
    {name:"Wendy's",domain:"wendys.com",category:"Food & Drink"},
    {name:"Chipotle",domain:"chipotle.com",category:"Food & Drink"},
    {name:"Dunkin'",domain:"dunkindonuts.com",category:"Food & Drink"},
    {name:"Red Bull",domain:"redbull.com",category:"Food & Drink"},
    {name:"Heineken",domain:"heineken.com",category:"Food & Drink"},
    {name:"Budweiser",domain:"budweiser.com",category:"Food & Drink"},
    {name:"Nestle",domain:"nestle.com",category:"Food & Drink"},
    {name:"Tim Hortons",domain:"timhortons.com",category:"Food & Drink"},
    {name:"Krispy Kreme",domain:"krispykreme.com",category:"Food & Drink"},
    {name:"Five Guys",domain:"fiveguys.com",category:"Food & Drink"},
    {name:"Nando's",domain:"nandos.com",category:"Food & Drink"},
    {name:"Greggs",domain:"greggs.co.uk",category:"Food & Drink"},
    {name:"Pret A Manger",domain:"pret.com",category:"Food & Drink"},
    // Fashion
    {name:"Nike",domain:"nike.com",category:"Fashion"},
    {name:"Adidas",domain:"adidas.com",category:"Fashion"},
    {name:"Puma",domain:"puma.com",category:"Fashion"},
    {name:"Gucci",domain:"gucci.com",category:"Fashion"},
    {name:"Louis Vuitton",domain:"louisvuitton.com",category:"Fashion"},
    {name:"Chanel",domain:"chanel.com",category:"Fashion"},
    {name:"Zara",domain:"zara.com",category:"Fashion"},
    {name:"H&M",domain:"hm.com",category:"Fashion"},
    {name:"Versace",domain:"versace.com",category:"Fashion"},
    {name:"Prada",domain:"prada.com",category:"Fashion"},
    {name:"Under Armour",domain:"underarmour.com",category:"Fashion"},
    {name:"New Balance",domain:"newbalance.com",category:"Fashion"},
    {name:"Converse",domain:"converse.com",category:"Fashion"},
    {name:"Levi's",domain:"levi.com",category:"Fashion"},
    {name:"Ralph Lauren",domain:"ralphlauren.com",category:"Fashion"},
    {name:"Tommy Hilfiger",domain:"tommy.com",category:"Fashion"},
    {name:"Calvin Klein",domain:"calvinklein.com",category:"Fashion"},
    {name:"Supreme",domain:"supremenewyork.com",category:"Fashion"},
    // Automotive
    {name:"Toyota",domain:"toyota.com",category:"Automotive"},
    {name:"Volkswagen",domain:"volkswagen.com",category:"Automotive"},
    {name:"BMW",domain:"bmw.com",category:"Automotive"},
    {name:"Mercedes-Benz",domain:"mercedes-benz.com",category:"Automotive"},
    {name:"Ford",domain:"ford.com",category:"Automotive"},
    {name:"Honda",domain:"honda.com",category:"Automotive"},
    {name:"Audi",domain:"audi.com",category:"Automotive"},
    {name:"Porsche",domain:"porsche.com",category:"Automotive"},
    {name:"Ferrari",domain:"ferrari.com",category:"Automotive"},
    {name:"Lamborghini",domain:"lamborghini.com",category:"Automotive"},
    {name:"Tesla",domain:"tesla.com",category:"Automotive"},
    {name:"Hyundai",domain:"hyundai.com",category:"Automotive"},
    {name:"Chevrolet",domain:"chevrolet.com",category:"Automotive"},
    {name:"Jeep",domain:"jeep.com",category:"Automotive"},
    {name:"Rolls-Royce",domain:"rolls-royce.com",category:"Automotive"},
    // Entertainment
    {name:"Disney",domain:"disney.com",category:"Entertainment"},
    {name:"Warner Bros",domain:"warnerbros.com",category:"Entertainment"},
    {name:"Marvel",domain:"marvel.com",category:"Entertainment"},
    {name:"Nintendo",domain:"nintendo.com",category:"Entertainment"},
    {name:"PlayStation",domain:"playstation.com",category:"Entertainment"},
    {name:"Xbox",domain:"xbox.com",category:"Entertainment"},
    {name:"LEGO",domain:"lego.com",category:"Entertainment"},
    {name:"HBO",domain:"hbo.com",category:"Entertainment"},
    {name:"ESPN",domain:"espn.com",category:"Entertainment"},
    {name:"BBC",domain:"bbc.co.uk",category:"Entertainment"},
    {name:"CNN",domain:"cnn.com",category:"Entertainment"},
    {name:"Paramount",domain:"paramount.com",category:"Entertainment"},
    {name:"Pixar",domain:"pixar.com",category:"Entertainment"},
    {name:"DreamWorks",domain:"dreamworks.com",category:"Entertainment"},
    // Finance
    {name:"Visa",domain:"visa.com",category:"Finance"},
    {name:"Mastercard",domain:"mastercard.com",category:"Finance"},
    {name:"American Express",domain:"americanexpress.com",category:"Finance"},
    {name:"HSBC",domain:"hsbc.com",category:"Finance"},
    {name:"JPMorgan",domain:"jpmorgan.com",category:"Finance"},
    {name:"Goldman Sachs",domain:"goldmansachs.com",category:"Finance"},
    {name:"Barclays",domain:"barclays.com",category:"Finance"},
    {name:"Citibank",domain:"citibank.com",category:"Finance"},
];
